### ISSUE TITLE
Document instructions for manual installation

### ISSUE THREAD

**Issue by HumairAK** [opendatahub-io/opendatahub-operator#107]
**Is your feature request related to a problem? Please describe.**
The operate-first team has come to the conclusion that for our needs we would prefer to manually install ODH rather than use OLM. See discussion [here](https://github.com/operate-first/apps/issues/206) for details. However there does not seem to be any docs indicating how one ought to go about doing this. 

**Describe the solution you'd like**
@LaVLaS has described the process for us [here](https://opendatahub.io/docs/getting-started/quick-installation.html). Which is essentially just doing a kustomize build & oc apply. I think the location of the manifests + this process (albeit minimal) should be mentioned in the docs under the installation instructions.

**Comment by nakfour** [comment]
we are migrating to https://issues.redhat.com/projects/ODH/summary can you please move all your open issues there.
