### ISSUE TITLE
Open Data Hub operator doesn't show up under Community Operators on operatorhub.io

### ISSUE THREAD

**Issue by pcarney8** [opendatahub-io/opendatahub-operator#110]
**Describe the bug**
https://operatorhub.io/?keyword=open+data+hub doesn't have this operator show up.

**To Reproduce**
1. Go to https://operatorhub.io/?keyword=open+data+hub or make it one word, it's not there.

**Expected behavior**
ODH Tile to show up

**Screenshots**
![Screenshot from 2021-03-24 14-46-13](https://user-images.githubusercontent.com/4354948/112367158-f5723480-8caf-11eb-93bf-cc970460aad2.png) <-- this is the tile that _should_ show up

**Additional context**
add it in here: https://github.com/operator-framework/community-operators/tree/master/community-operators

**Comment by nakfour** [comment]
@pcarney8 Open Data Hub is not available on operatorhub.io, it is only available on Operatohub on Openshift
