### ISSUE TITLE
Installation fails with multiple OperatorGroups issue

### ISSUE THREAD

**Issue by haf-tech** [opendatahub-io/opendatahub-operator#128]
**Describe the bug**
After installing OpenDataHub via OperatorHub in OCP 4.6 the following error message occur 

```
Failed: csv created in namespace with multiple operatorgroups, can't pick one automatically
```

During installation the default parameters set / not changed.

**To Reproduce**

1. Search Open Data Hub in OperatorHub
2. Install without modifying the values
3. wait some seconds

**Expected behavior**
No error :-)

**Screenshots**

```
oc get operatorgroup -A 
NAMESPACE                              NAME                               AGE
apicurito                              apicurito                          17h
gitlab-config                          gitlab-config-lwqpm                8d
gitops-config                          sealed-secrets-operator-helm       17h
instana-agent                          instana-agent-rlhvv                8d
openshift-monitoring                   openshift-cluster-monitoring       8d
openshift-operator-lifecycle-manager   olm-operators                      8d
openshift-operators-redhat             openshift-operators-redhat-gxcct   17h
openshift-operators                    global-operators                   8d
openshift-operators                    opendatahub                        3m54s
```

**Additional context**

* OCP 4.6
* OpenDataHub 1.0.10

Installing the operator in an other namespace, like `odh` was also not successful, with the error message, can not observe the own namespace
After the solution of this issue, we have to update the docu:
https://opendatahub.io/docs/getting-started/quick-installation.html

**Comment by nakfour** [comment]
@haf-tech did you install ODH in a new namespace called opendatahub?

**Comment by tumido** [comment]
Did you try deploying a Kfdef resource into the `openshift-operators` namespace?

It seems to me like [this resource](https://github.com/opendatahub-io/odh-manifests/blob/master/odh-common/base/operatorgroup.yaml) got unintentionally deployed into that namespace...

**Comment by haf-tech** [comment]
@nakfour see my comment 
> Installing the operator in an other namespace, like odh was also not successful, with the error message, can not observe the own namespace
I tried it with `odh`. Is "only" `opendatahub` supported?

**Comment by tumido** [comment]
@haf-tech any namespace should be supported. I think you won't get any new operator group created if you "just install" the operator itself with the default settings. Your conflict comes from the presence of 2 operator group resources in the `openshift-operators` namespace:

> ```
> openshift-operators                    global-operators                   8d
> openshift-operators                    opendatahub                        3m54s
> ```

However the problematic [`opendatahub` OperatorGroup resource](https://github.com/opendatahub-io/odh-manifests/blob/master/odh-common/base/operatorgroup.yaml) gets created only after you deploy a `KfDef` resource (with a `odh-common` application in it). It seems to me like you have a KfDef resource in your `openshift-operators` namespace. Is that the case?

**Comment by haf-tech** [comment]
yeah, using the default template and creating the `KfDef` instance in the same namespace where the operator is installed will result in this problem. 
So creating beforehand an own namespace for `KfDef` will avoid this issue

probably this should be emphasized clearly to create `KfDef` in another namespace :)
