### ISSUE TITLE
Open Data Hub operator install fails on OpenShift 4.7.4

### ISSUE THREAD

**Issue by schnn** [opendatahub-io/opendatahub-operator#132]
Install Open Data Hub operator 
Create kfdef with https://raw.githubusercontent.com/kubeflow/manifests/v1.3-branch/distributions/kfdef/kfctl_openshift.master.kfptekton.yaml

application-controller-stateful-set-0              0/1     CreateContainerError   0          40m

Events:
  Type     Reason          Age                  From               Message
  ----     ------          ----                 ----               -------
  Normal   Scheduled       40m                  default-scheduler  Successfully assigned kubeflow/application-controller-stateful-set-0 to worker2.dewclaw.cp.fyre.ibm.com
  Normal   AddedInterface  40m                  multus             Add eth0 [10.254.20.30/22]
  Normal   Pulled          40m                  kubelet            Successfully pulled image "gcr.io/kubeflow-images-public/kubernetes-sigs/application:1.0-beta" in 6.087524932s
  Warning  Failed          40m                  kubelet            Error: container create failed: time="2021-05-17T04:32:59Z" level=error msg="container_linux.go:366: starting container process caused: chdir to cwd (\"/root/\") set in config.json failed: permission denied"
  Normal   Pulled          40m                  kubelet            Successfully pulled image "gcr.io/kubeflow-images-public/kubernetes-sigs/application:1.0-beta" in 1.298748775s
  Warning  Failed          40m                  kubelet            Error: container create failed: time="2021-05-17T04:33:01Z" level=error msg="container_linux.go:366: starting container process caused: chdir to cwd (\"/root/\") set in config.json failed: permission denied"
  Warning  Failed          40m                  kubelet            Error: container create failed: time="2021-05-17T04:33:17Z" level=error msg="container_linux.go:366: starting container process caused: chdir to cwd (\"/root/\") set in config.json failed: permission denied"
  Normal   Pulled          40m                  kubelet            Successfully pulled image "gcr.io/kubeflow-images-public/kubernetes-sigs/application:1.0-beta" in 911.920594ms
  Warning  Failed          39m                  kubelet            Error: container create failed: time="2021-05-17T04:33:32Z" level=error msg="container_linux.go:366: starting container process caused: chdir to cwd (\"/root/\") set in config.json failed: permission denied"
  Normal   Pulled          39m                  kubelet            Successfully pulled image "gcr.io/kubeflow-images-public/kubernetes-sigs/application:1.0-beta" in 833.160798ms
  Normal   Pulled          39m                  kubelet            Successfully pulled image "gcr.io/kubeflow-images-public/kubernetes-sigs/application:1.0-beta" in 853.684678ms
  Warning  Failed          39m                  kubelet            Error: container create failed: time="2021-05-17T04:33:46Z" level=error msg="container_linux.go:366: starting container process caused: chdir to cwd (\"/root/\") set in config.json failed: permission denied"
  Normal   Pulled          39m                  kubelet            Successfully pulled image "gcr.io/kubeflow-images-public/kubernetes-sigs/application:1.0-beta" in 834.434988ms
  Warning  Failed          39m                  kubelet            Error: container create failed: time="2021-05-17T04:34:01Z" level=error msg="container_linux.go:366: starting container process caused: chdir to cwd (\"/root/\") set in config.json failed: permission denied"
  Normal   Pulled          39m                  kubelet            Successfully pulled image "gcr.io/kubeflow-images-public/kubernetes-sigs/application:1.0-beta" in 834.092803ms
  Warning  Failed          39m                  kubelet            Error: container create failed: time="2021-05-17T04:34:16Z" level=error msg="container_linux.go:366: starting container process caused: chdir to cwd (\"/root/\") set in config.json failed: permission denied"
  Normal   Pulled          38m                  kubelet            Successfully pulled image "gcr.io/kubeflow-images-public/kubernetes-sigs/application:1.0-beta" in 791.863246ms
  Warning  Failed          38m                  kubelet            Error: container create failed: time="2021-05-17T04:34:29Z" level=error msg="container_linux.go:366: starting container process caused: chdir to cwd (\"/root/\") set in config.json failed: permission denied"
  Normal   Pulling         26s (x171 over 40m)  kubelet            Pulling image "gcr.io/kubeflow-images-public/kubernetes-sigs/application:1.0-beta"

**Comment by nakfour** [comment]
@schnn yes we are aware of these bugs on OCP 4.6/4.7 and its all captured in this issue https://github.com/kubeflow/manifests/issues/1867
At the moment KF 1.3 only works on OCP 4.5
