### ISSUE TITLE
cuda-11.0.3 overlay cascading Builds lastTriggeredImageID

### ISSUE THREAD

**Issue by dmarcus-wire** [opendatahub-io/opendatahub-operator#133]
**Describe the bug**
Deploying ODH Operator with the `- cuda-11.0.3` overlay in the notebook-images results in infinite re-Builds. 

**To Reproduce**
From the ODH Operator, include the 'cuda-11.0.3' overlay in the kfdef (example below) and wait for the notebook images to build

----EXAMPLE KFDEF----
apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  name: opendatahub
  namespace: odh-cuda-notebooks
spec:
  applications:
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odh-common
      name: odh-common
    - kustomizeConfig:
        parameters:
          - name: s3_endpoint_url
            value: s3.odh.com
        repoRef:
          name: manifests
          path: jupyterhub/jupyterhub
      name: jupyterhub
    - kustomizeConfig:
        overlays:
          - additional
          - cuda-11.0.3
        repoRef:
          name: manifests
          path: jupyterhub/notebook-images
      name: notebook-images
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odh-dashboard
      name: odh-dashboard
  repos:
    - name: kf-manifests
      uri: 'https://github.com/kubeflow/manifests/tarball/v1.2-branch'
    - name: manifests
      uri: 'https://github.com/opendatahub-io/odh-manifests/tarball/v1.0.10'
----END KFDEF----
 

**Expected behavior**
cuda notebook BuildConfigs are built and completed, making them available through the ODH Jupyter Spawner and without recurring Builds every few minutes.

**Screenshots**

**Additional context**
The BuildConfig for these cuda notebooks includes a field triggers.imageChange.lastTriggeredImageID that appears to be triggering the re-builds

lastTriggeredImageID is deprecated in 4.7 https://issues.redhat.com/browse/BUILD-189 but the issue still persists from testing the KfDef on a 4.7 cluster

Workarounds that stop the continuous builds: 
1) after deployed, comment the '- cuda-11.0.3' overlay out of the KfDef 
or 2) run an oc apply -f on the build chain that creates these cuda enabled notebooks.

**Comment by nakfour** [comment]
we are migrating to https://issues.redhat.com/projects/ODH/summary can you please move all your open issues there.
