### ISSUE TITLE
In case there are multiple `KfDef`s on a cluster and one of them is faulty - operators gets stuck on the faulty one

### ISSUE THREAD

**Issue by tumido** [opendatahub-io/opendatahub-operator#135]
**Describe the bug**
In Operate First we use multiple `KfDef`s on the same cluster, when operator tries to apply them it basically loops through them. The problem is when one of the `KfDef`s is faulty and fails to apply (imagine a change/patch that is not allowed - like a change in storage class on a PVC), the operator gets stuck on this faulty `KfDef` and keeps retrying to apply it. That means it never gets to apply the other `KfDef`s and makes them wait to be processed - which never happens. 

```
time="2021-06-03T15:23:43Z" level=warning msg="Encountered error applying application jupyterhub:  (kubeflow.error): Code 500 with message: Apply.Run : error when applying patch:\n{\"metadata\":{\"annotations\":{\"kubectl.kubernetes.io/last-applied-configuration\":\"{\\\"apiVersion\\\":\\\"v1\\\",\\\"kind\\\":\\\"PersistentVolumeClaim\\\",\\\"metadata\\\":{\\\"annotations\\\":{\\\"kfctl.kubeflow.io/kfdef-instance\\\":\\\"opendatahub.opf-jupyterhub\\\",\\\"volume.beta.kubernetes.io/storage-class\\\":\\\"moc-nfs-csi\\\"},\\\"labels\\\":{\\\"component.opendatahub.io/name\\\":\\\"jupyterhub\\\",\\\"opendatahub.io/component\\\":\\\"true\\\"},\\\"name\\\":\\\"jupyterhub-db\\\",\\\"namespace\\\":\\\"opf-jupyterhub\\\"},\\\"spec\\\":{\\\"accessModes\\\":[\\\"ReadWriteOnce\\\"],\\\"resources\\\":{\\\"requests\\\":{\\\"storage\\\":\\\"1Gi\\\"}}}}\\n\",\"volume.beta.kubernetes.io/storage-class\":\"moc-nfs-csi\"}}}\nto:\nResource: \"/v1, Resource=persistentvolumeclaims\", GroupVersionKind: \"/v1, Kind=PersistentVolume...
time="2021-06-03T15:23:43Z" level=warning msg="Will retry in 25 seconds."
```
  
**Expected behavior**
If operator faces an error, it should stop retrying to apply a faulty `KfDef` after a few attempts and not indefinitely.

**Screenshots**
[operator_pod_log.txt](https://github.com/opendatahub-io/opendatahub-operator/files/6592755/log.6.txt)

**Additional context**
Related to: https://github.com/operate-first/support/issues/260

**Comment by nakfour** [comment]
we are migrating to https://issues.redhat.com/projects/ODH/summary can you please move all your open issues there.

**Comment by tumido** [comment]
Migrated to: https://issues.redhat.com/browse/ODH-404
