### ISSUE TITLE
Clean up on deleting the operator

### ISSUE THREAD

**Issue by nakfour** [opendatahub-io/opendatahub-operator#15]
We have many namespaces and webhooks left behind after the operator is deleted.
1. All namespaces outside the main deployment, such as cert-manager, airflow, istio ..etc
2. all the mutatingwebhookconfigurations.admissionregistration.k8s.io and validatingwebhookconfigurations.admissionregistration.k8s.io are left, and those cause issues

**Comment by LaVLaS** [comment]
Closing since this is no longer an issue
