### ISSUE TITLE
Compatibility and interaction with Red Hat Openshift Service Mesh Operator

### ISSUE THREAD

**Issue by shalberd** [opendatahub-io/opendatahub-operator#151]
In a knowledgebase article about installing Kubeflow via Open Data Hub Operator on Openshift, there is a Requirement-section that says:

https://developers.redhat.com/articles/2021/05/28/how-install-kubeflow-12-red-hat-openshift#

**You should not have an existing project named istio-system as Kubeflow deploys Istio along with configurations.
You should not have an existing Istio service mesh, because it will lead to name collisions.**

Now, we are planning to have the Red Hat OpenShift Service Mesh installed as part of an overall microservice-ready setup:

https://catalog.redhat.com/software/operators/detail/5ec53e8c110f56bd24f2ddc4

Red Hat OpenShift Service Mesh - 
Allows you to connect, secure, control, and observe the microservices that 
comprise your applications. The Service Mesh Operator defines and monitors the 
ServiceMeshControlPlane resources that manage the deployment, updating, and 
deletion of the Service Mesh components. It is based on the open source Istio project.

https://docs.openshift.com/container-platform/4.9/service_mesh/v2x/installing-ossm.html

Question: Does that mean that Kubeflow via Open Data Hub Operator and Red Hat Service Mesh cannot work together?

I found another 2020 article 

https://developers.redhat.com/blog/2020/04/24/integrating-kubeflow-with-red-hat-openshift-service-mesh#red_hat_openshift_service_mesh

that writes about integrating ODH with Red Hat Service Mesh, so question is why the 2021 Dev article does not mention that.

**Comment by VaishnaviHire** [comment]
@shalberd We were able to integrate Service Mesh Operator with Kubeflow (for KF1.3 and KF1.4). It will be available in the next release of ODH - v1.2

Following are the links to the ServiceMesh PRs:
https://github.com/opendatahub-io/odh-manifests/pull/484
https://github.com/opendatahub-io/manifests/pull/77
https://github.com/opendatahub-io/manifests/pull/81

**Comment by shalberd** [comment]
as mentioned in the pull requests, we are using multiple namespaces / meshes with ServiceMeshControlPlane and ServiceMeshMemberRoll in those respective namespaces. Having a configurable namespace parameter would be great,
