### ISSUE TITLE
ODH Operator Re-architecture

### ISSUE THREAD

**Issue by LaVLaS** [opendatahub-io/opendatahub-operator#156]
- [x] Create prototype branch for re-architecture of operator code
- [x] #157
- [ ] #158
- [x] Implement CI/CD for building and testing PRs
- [x] #159

**Comment by codekow** [comment]
Isn't the [kubeflow operator dead](https://github.com/kubeflow/kfctl/issues/501)? 

Which would mean that kfdefs are also dead (CRDs are processed by the operator)?

**Comment by shalberd** [comment]
@codekow Very good question, looks like it, as the ODH folks will go with their own controller soon.

Hopefully, things like proxy support and custom CA trust will be considered there as well.

**Comment by VaishnaviHire** [comment]
Closing this as we have duplicate tracker https://github.com/opendatahub-io/opendatahub-operator/issues/158
