### ISSUE TITLE
Create a process/plan for KF operator merges and rebases.

### ISSUE THREAD

**Issue by nakfour** [opendatahub-io/opendatahub-operator#16]

**Comment by LaVLaS** [comment]
Image of ![FINAL DRAFT  ODH git workflow](https://user-images.githubusercontent.com/2432396/81818231-c3267100-94fb-11ea-9869-2ba7d44342ce.png)

**Comment by vpavlin** [comment]
Should this diagram go to CONTRIBUTING.md?

**Comment by LaVLaS** [comment]
> Should this diagram go to CONTRIBUTING.md?

Yes. I'll check to see if there is some markdown support for a basic flow chart so we can update it if needed. Otherwise, I'll just add the image to CONTRIBUTING
