### ISSUE TITLE
Report status of KFDef Object

### ISSUE THREAD

**Issue by strangiato** [opendatahub-io/opendatahub-operator#166]
**Is your feature request related to a problem? Please describe.**
It is unclear what the status of the KFDef object is once it has been created unless you follow the operator logs.  Issues with a KFDef are unclear and unreported to the end user that created the object unless they are able to view the operator logs (many users will only have access to the namespace in which they are attempting to install the KFDef).

**Describe the solution you'd like**
Report the status of the KFDef in the status section of the object.  Object should have a clear indication of when it is Syncing/Progressing, Degraded (issue with a configuration or unable to apply a change), and successfully synced.

The KFDef deployment could include several status checks such as "manifests accessible", "applications valid", and "applications synced".

The status should also report information back to the user in the case that there is an error or a mis-configuration in the KFDef object.

**Describe alternatives you've considered**

**Additional context**

It would be great to have a custom health check in Argo (something I would be willing to contribute) but that could be problematic with an API/Kind name conflict with the upstream KFDef object.

**Comment by VaishnaviHire** [comment]
No longer relevant. Status is being tracked as part of v2.x operator
