### ISSUE TITLE
Implementing deployment of manifests

### ISSUE THREAD

**Issue by VaishnaviHire** [opendatahub-io/opendatahub-operator#167]

**Comment by shalberd** [comment]
It'd be nice if this opportunity were used to 

a) add handling custom PKI CA Cert trust handling in golang, for all download-type scenarios. 

https://stackoverflow.com/questions/40051213/where-is-golang-picking-up-root-cas-from

Related issues

https://github.com/opendatahub-io/jupyterhub-odh/issues/137#issuecomment-1197989697

https://github.com/elyra-ai/elyra/issues/2797#issuecomment-1192290490

https://github.com/opendatahub-io/odh-manifests/issues/575#

b) add API-key type Http-Basic-Authentication support for all http requests
