### ISSUE TITLE
Implement OAuthClient generation in the SecretGenerator controller

### ISSUE THREAD

**Issue by samuelvl** [opendatahub-io/opendatahub-operator#175]
**Is your feature request related to a problem? Please describe.**
The [ODH dashboard](https://github.com/opendatahub-io/odh-dashboard/issues/479) needs a dedicated `OAuthClient` object. However this object contains sensitive information (oauth client secret). Use the SecretGenerator controller to create this object.

**Describe the solution you'd like**
Annotate a secret with the `secret-generator.opendatahub.io/oauth-client-route` annotation to create the corresponding `OAuthClient` object:

```
apiVersion: v1
kind: Secret
metadata:
  name: example
  annotations:
    secret-generator.opendatahub.io/oauth-client-route: "odh-dashboard"
type: Opaque

-> controller -> creates ->

apiVersion: oauth.openshift.io/v1
kind: OAuthClient
metadata:
  name: <name of the route>
grantMethod: auto
redirectURIs:
- <filled by the SecretGenerator controller>
secret: <filled by the SecretGenerator controller>
```

**Comment by VaishnaviHire** [comment]
@samuelvl  A quick question regarding implementation- Should the annotation be added to the user created Secret or the controller generated secret ?

**Comment by samuelvl** [comment]
@VaishnaviHire The user will add the annotation. In the dashboard case a new secret will be created here -> https://github.com/opendatahub-io/odh-dashboard/tree/main/manifests/overlays/authentication
