### ISSUE TITLE
[feature/update-sdk] Test and Update operator-sdk scorecard

### ISSUE THREAD

**Issue by VaishnaviHire** [opendatahub-io/opendatahub-operator#189]
The `operator-sdk` scorecard command executes tests on the operator based upon a configuration file and test images. As the operator-sdk support is updated as part of https://github.com/opendatahub-io/opendatahub-operator/issues/176, investigate if -
-  scorecard [built-in tests](https://sdk.operatorframework.io/docs/testing-operators/scorecard/#built-in-tests) are success with the existing bundle.
- Add custom tests if required

**Comment by maroroman** [comment]
Looks like the basic built-in scorecard tests run successfully with the current bundle. So the next step would be to decide what tests we want to add outside of e2e testing. @VaishnaviHire  

I am not sure whether these belong in e2e or scorecard, but I would try creating tests for comparing the applied kfdef with the state of the cluster.

Also, do we want to keep the test images required for scorecard in this repository?
