### ISSUE TITLE
[feature/update-sdk] Add support for bundling the odh-manifest into the operator image

### ISSUE THREAD

**Issue by LaVLaS** [opendatahub-io/opendatahub-operator#196]
**Is your feature request related to a problem? Please describe.**
The current operator requires that a user always provide a remote repository reference in the `kfdef` to pull in for deployment.    This can cause issues when there are network restrictions or connectivity issues.  Now that ODH has an odh-core configuration that should be the default install of ODH, we should be bundling the tarball for [odh-manifests](https://github.com/opendatahub-io/odh-manifests) in the operator image as the default (fallback) manifest when no repo reference is provided by the user

**Describe the solution you'd like**
- Update the operator image build to include a tarball, `odh-manifests.tar.gz`, of the tagged [odh-manifests](https://github.com/opendatahub-io/odh-manifests)  container
- Update the operator code so that the `kfdef.spec.repos` will have a default value that pulls from the local manifest if the user does not specify the location
  ```yaml
  spec:
    repos:
      - name: manifests
        uri: file:///opt/manifests/odh-manifests.tar.gz
  ```

This must target the changes included in the [update-sdk branch](https://github.com/opendatahub-io/opendatahub-operator/tree/feature/update-sdk)

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by maroroman** [comment]
> Update the operator image build to include a tarball, odh-manifests.tar.gz, of the tagged [odh-manifests](https://github.com/opendatahub-io/odh-manifests) container

@LaVLaS Would we update this tarball on each manifests release or should this be automated?
