### ISSUE TITLE
[feature/update-sdk] Add github workflow to sync Dashboard CRDs

### ISSUE THREAD

**Issue by VaishnaviHire** [opendatahub-io/opendatahub-operator#200]
Automate the process to sync Dashboard CRDs in the  manifests using Github workflows.

The goal is to open a PR in the opendatahub-operator repo when crds are updated in the [dashboard](https://github.com/opendatahub-io/odh-dashboard/tree/main/manifests/crd) repo.

**Comment by shalberd** [comment]
really nice to see CRD-type solutions, neat from an architectural perspective
