### ISSUE TITLE
Quick Installation documentation is unclear 

### ISSUE THREAD

**Issue by dmarcus-wire** [opendatahub-io/opendatahub-operator#204]
**Describe the bug**
The quick installation step #6 "It is important to switch to the namespace you created earlier. Installing in the “OpenShift Operators” namespace will result in a fatal error similar to “csv created in namespace with multiple operatorgroups, can’t pick one automatically”." makes it seem like you want to install the operator in 'odh' project.

**To Reproduce**
Go to https://opendatahub.io/docs/getting-started/quick-installation.html 
Go to step 6

**Expected behavior**
Clearly illustrate/explain install the operator in 'openshift-operators'
Clearly illustrate/explain deploy a kfdef in a custom project (not openshift-operators), like project: odh

**Comment by dmarcus-wire** [comment]
Please also update the pre-installation requirements specifically for operational "Image Registry" and "Persistent Storage". It does not need to be comprehensive for every combination OCP installs, but worthwhile mentions.

**Comment by maroroman** [comment]
This will be updated as part of a comprehensive odh website documentation update: https://github.com/opendatahub-io/opendatahub.io/issues/21

**Comment by VaishnaviHire** [comment]
This is no longer an issue with v2 operator
