### ISSUE TITLE
Move operator releases to the "fast" OLM channel

### ISSUE THREAD

**Issue by LaVLaS** [opendatahub-io/opendatahub-operator#219]
**Is your feature request related to a problem? Please describe.**
Now that ODH, will focus on bi-weekly rapid releases with no support for previous release (<= n-1), we are dropping the `stable` channel and only pushing to `rolling`.  To put us inline with the OpenShift OLM channel naming  [recommendations](https://olm.operatorframework.io/docs/best-practices/channel-naming/#example-1)

**Describe the solution you'd like**
With the next release, we should 
1. drop the `stable` and `rolling` channels officially
2. Start pushing to `fast` channel

**Describe alternatives you've considered**
We could keep pushing to the `rolling` channel as that has the same functionality as a `fast` channel

**Additional context**
N/A

**Comment by VannTen** [comment]
Related to the documentation you linked, should we consider a `candidate` channel as well ? (for continuous testing, maybe ?)

**Comment by zdtsw** [comment]
do we still need this issue? 
v2.X  is set to use "fast"
v1.X  is planned to stop new release after 1.11
