### ISSUE TITLE
v1.5.0 broke the installation using kubeflow manifest

### ISSUE THREAD

**Issue by tks-ai** [opendatahub-io/opendatahub-operator#224]
hi , i would like to describe my problem using the kfDef like below with odh-operator v1.5.0

https://github.com/opendatahub-io/manifests/blob/v1.6-branch-openshift/openshift/kfdef/kfctl_openshift_v1.5.0_odh.yaml

i recognized that from v1.5.0 ,ownerReferrence to link to kfDef it uses will be inserted to every resource during deploying.
this may make kubeflow stucks.
As you know kubeflow's component will be deployed to defferent namespaces(Ex: kubeflow,istio-sytem,cert-manager,kube-system...)

While deploying istio , it requires its ownerReferrence kfDef exists in istio-system namespace, but in my case kfDef is holded by kubeflow namespace , if the related kfDef cannot be found , any deployment created by istio will be deleted ,but the operator will try to create it again ,so it loops forever...  

Considered to split the istio part of kfDef to istio-system, but istio deploy some of its stuffs to kube-system namespace, so this wont help me.

Kubeflow is considered as a part of OpenDataHub? but this release seems break the relationship with kubeflow.
Is there any smart way?

**Comment by zdtsw** [comment]
@tks-ai can we have this issue closed and move to v2 operator?
