### ISSUE TITLE
The ODH operator deployment should use non-overlapping label selector

### ISSUE THREAD

**Issue by astefanutti** [opendatahub-io/opendatahub-operator#230]
**Describe the bug**

The operator deployment is configured with the default label selector, as generated by the kubebuilder scaffolding, i.e.:  

```yaml
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
```

This selector can intersect with other deployments, for instance the CodeFlare operator, which leads to issues where selection based on this selector returns more than expected.

**To Reproduce**

1. Install the Open Data Hub operator
2. Install the CodeFlare operator
3. Go to the Open Data Hub operator deployment details page > Pods tab

**Expected behavior**

Pods other than that of the ODH operator are listed.

**Screenshots**

<img width="1465" alt="Screenshot 2023-05-30 at 16 06 51" src="https://github.com/opendatahub-io/opendatahub-operator/assets/366207/9c1dc6a7-8b33-4ec2-b9a7-b30198c0f050">

**Additional context**

This also affect the metrics service pod selections:

<img width="1616" alt="Screenshot 2023-06-08 at 12 09 04" src="https://github.com/opendatahub-io/opendatahub-operator/assets/366207/1742c6d8-92ce-4c9b-8bc0-cb006ed88c66">

The selector should be changed, so it's disjunct from any other deployments, ideally following Kubernetes recommended labels: https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/

The main challenge is that deployment label selector is immutable once created, which will break the rollout deployment performed during the next OLM upgrade: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#label-selector-updates. With some more background available at kubernetes/kubernetes#50808.

A possible work-around is to renamed the operator deployment, according to OLM recommendation: https://github.com/operator-framework/operator-lifecycle-manager/issues/952#issuecomment-639657949.

**Comment by zdtsw** [comment]
@astefanutti is this still a valid issue?

**Comment by astefanutti** [comment]
@zdtsw I think so yes. The operator still uses the default `control-plane: controller-manager` label selector.

**Comment by zdtsw** [comment]
> @zdtsw I think so yes. The operator still uses the default `control-plane: controller-manager` label selector.

thanks! got confused when checking the description of "how to reproduce".

**Comment by astefanutti** [comment]
> thanks! got confused when checking the description of "how to reproduce".

Ah yes, the description is out-dated now with v2, and we fixed it on the CodeFlare operator side, still it'd be valuable the ODH operator fixes it, as chances are the default label selector can intersect with other deployments / pods.

**Comment by AjayJagan** [comment]
here is the JIRA counterpart for the same issue : https://issues.redhat.com/browse/RHOAIENG-405
