### ISSUE TITLE
Operator log reports error "Cannot create watch for resources Deployment extensions/v1beta1"

### ISSUE THREAD

**Issue by LaVLaS** [opendatahub-io/opendatahub-operator#24]
Builds of the latest operator as of the pre-0.6.1 releases reports the error below. This does not appear to have any noticeable affects on deployments.

```
time="2020-05-19T06:23:30Z" level=error msg="Cannot create watch for resources Deployment extensions/v1beta1: no matches for kind \"Deployment\" in version \"extensions/v1beta1\"."
```

**Comment by vpavlin** [comment]
Here: https://github.com/kubeflow/kfctl/blob/aaba770b461a27fc59d4a7960df48a3da003eda2/pkg/controller/kfdef/const.go#L20
