### ISSUE TITLE
Ability to create Dashboard CRs as part of DSCInitialization controller

### ISSUE THREAD

**Issue by VaishnaviHire** [opendatahub-io/opendatahub-operator#250]
Dashboard CRs are being deployed as part of [odh-deployer](https://github.com/red-hat-data-services/odh-deployer/tree/main/odh-dashboard). Assuming these manifests would be included / bundled in operator pod as part of #249 , update controller to identify deployment [env](https://github.com/red-hat-data-services/odh-deployer/blob/main/deploy.sh#L70) and apply CRs accordingly.

**Comment by jharmison-redhat** [comment]
Doing this after #253
