### ISSUE TITLE
Deploy Monitoring resources

### ISSUE THREAD

**Issue by VaishnaviHire** [opendatahub-io/opendatahub-operator#252]
Deploy Monitoring resources for managed services of odh 

- Create watch for smtp secret
- Fix issues deploying blackbox-exporter and prometheus deployment

**Comment by zdtsw** [comment]
Do we need watch on `pagerDutySecret` as well? only `smtpSecret` enough?

**Comment by zdtsw** [comment]
think the problem for blackbox-exporter the issue is the path of alertmanager.yaml does not exsit as  `/etc/alertmanager/alertmanager.yml`
as in https://github.com/VaishnaviHire/odh-manifests/blob/rearch_manifests/monitoring/prometheus/prometheus.yaml#L205
