### ISSUE TITLE
Deploy Dashboard CRDs

### ISSUE THREAD

**Issue by VaishnaviHire** [opendatahub-io/opendatahub-operator#253]

**Comment by jharmison-redhat** [comment]
Going to implement the CRDs as elements of the ODH OLM bundle as discussed - I'm on this right now.

**Comment by VaishnaviHire** [comment]
Current CSV for ODH - https://github.com/opendatahub-io/opendatahub-operator/blob/master/bundle/manifests/opendatahub-operator.clusterserviceversion.yaml#L253

**Comment by VaishnaviHire** [comment]
Done as part of #249
