### ISSUE TITLE
Deploying opendatahub-operator on an airgapped OpenShift environment

### ISSUE THREAD

**Issue by BlueCog** [opendatahub-io/opendatahub-operator#259]
Hello Everyone,

I am facing an issue while deploying the opendatahub-operator on an air-gapped OpenShift Cluster (v4.11) and am seeking help to resolve it.

Here are the steps I've followed so far:

- Pulled kube-rbac-proxy:v0.13.0 and opendatahub-operator:v1.6.0 images, and made them available in our internal registry.
- Created an image directive inside the [kustomization.yaml](https://github.com/opendatahub-io/opendatahub-operator/blob/master/config/default/kustomization.yaml) to reflect the old and new image locations.
- Deployed the opendatahub-operator to OpenShift using the command: kustomize build . | oc apply -f -. This resulted in a successfully deployed Operator with two containers within a single pod.

Here are the logs for the opendatahub-operator pod (container: kube-rbac-proxy):

```
I0622 14:27:48.941710 1 main.go:186] Valid token audiences:
I0622 14:27:48.941801 1 main.go:316] Generating self signed cert as no cert is provided
I0622 14:27:49.919515 1 main.go:366] Starting TCP socket on 0.0.0.0:8443
I0622 14:27:49.919808 1 main.go:373] Listening securely on 0.0.0.0:8443
```

Next, I attempted to deploy using [the kubeflow deploy example](https://raw.githubusercontent.com/kubeflow/manifests/v1.3-branch/distributions/kfdef/kfctl_openshift_v1.3.0.yaml) from https://dev.operatorhub.io/operator/opendatahub-operator, targeting the kubeflow namespace. However, there wasn't any observable activity or change.

Here are the logs for the opendatahub-operator pod (container: manager):

```
2023-06-22T14:54:21.353Z INFO controllers.KfDef Conflict during finalizer removal, retrying.
2023-06-22T14:54:21.357Z INFO controllers.KfDef Conflict during finalizer removal, retrying.
2023-06-22T14:54:21.360Z ERROR controllers.KfDef error removing finalizer {"error": "Operation cannot be fulfilled on kfdefs.kfdef.apps.kubeflow.org \"kubeflow\": StorageError: invalid object, Code: 4, Key: /kubernetes.io/kfdef.apps.kubeflow.org/kfdefs/kubeflow/kubeflow, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 40813429-da65-4bed-a66c-9c7d9e4b42e9, UID in object meta: "}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/internal/controller/controller.go:227
2023-06-22T14:54:21.360Z ERROR controller.kfdef-controller Reconciler error {"reconciler group": "kfdef.apps.kubeflow.org", "reconciler kind": "KfDef", "name": "kubeflow", "namespace": "kubeflow", "error": "Operation cannot be fulfilled on kfdefs.kfdef.apps.kubeflow.org \"kubeflow\": StorageError: invalid object, Code: 4, Key: /kubernetes.io/kfdef.apps.kubeflow.org/kfdefs/kubeflow/kubeflow, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 40813429-da65-4bed-a66c-9c7d9e4b42e9, UID in object meta: "}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/internal/controller/controller.go:227
2023-06-22T14:54:21.360Z INFO controllers.KfDef Reconciling KfDef resources {"Request.Namespace": "kubeflow", "Request.Name": "kubeflow"}
2023-06-22T14:54:21.365Z INFO controllers.KfDef Reconciling KfDef resources {"Request.Namespace": "kubeflow", "Request.Name": "kubeflow"}
``` 
and

```
17:24 2023-06-22T14:49:59.178Z ERROR controllers.KfDef failed to build kfApp from URI {"uri": "/tmp/kubeflow/kubeflow/config.yaml", "error": "couldn't generate KfApp: (kubeflow.error): Code 500 with message: could not sync cache. Error: (kubeflow.error): Code 400 with message: couldn't download URI https://github.com/kubeflow/manifests/archive/v1.3.0.tar.gz: Get \"https://github.com/kubeflow/manifests/archive/v1.3.0.tar.gz\": dial tcp 140.82.121.4:443: connect: connection timed out"}
github.com/opendatahub-io/opendatahub-operator/controllers/kfdef%2eapps%2ekubeflow%2eorg.(*KfDefReconciler).Reconcile 
```

I tried searching for solutions based on the error logs, but have not had any success yet.

Also, I noted that the [CRD ](https://raw.githubusercontent.com/kubeflow/manifests/v1.3-branch/distributions/kfdef/kfctl_openshift_v1.3.0.yaml)references the URI https://github.com/kubeflow/manifests/archive/v1.3.0.tar.gz. When looking at the error logs I suspect that this could also be something that needs to be provided internally? And if yes, could I override the image's via the CRD? Or do i need to host & edit the manifest(s) myself?

I'd greatly appreciate any assistance or insight you could provide regarding this issue. Thank you in advance!

**Comment by BlueCog** [comment]
Ok... i've continued my search ;)

- I've downloaded the https://github.com/kubeflow/manifests/archive/v1.3.0.tar.gz file from the [CRD](https://raw.githubusercontent.com/kubeflow/manifests/v1.3-branch/distributions/kfdef/kfctl_openshift_v1.3.0.yaml)
- Pulled all needed images, and made them available in our internal registry.
- Created an image directive inside the kustomization.yaml files based on what is defined in the [CRD](https://raw.githubusercontent.com/kubeflow/manifests/v1.3-branch/distributions/kfdef/kfctl_openshift_v1.3.0.yaml)
- Hosted the now edited v1.3.0.tar.gz file internally 
- Defined the new location in the CRD
- Added certificate's to the Operator (to communicate with the internal repo of the  v1.3.0.tar.gz file)
- Applied the edited CRD again 

Now i see the operator is pulling the file and starting to do stuff. 

Attached are the logs of the operator. 

It seems the operator "hangs" on the message: `Error evaluating kustomization manifest for istio-stack: error mapping rest config no matches for kind \"CustomResourceDefinition\" in version \"apiextensions.k8s.io/v1beta1\" `

```
time="2023-06-23T11:05:14Z" level=info msg="Deploying application openshift-scc"
time="2023-06-23T11:05:14Z" level=info msg="Inside the transform function"
I0623 11:05:22.805760 1 request.go:668] Waited for 8.195969853s due to client-side throttling, not priority and fairness, request: GET:https://172.30.0.1:443/apis/datamover.oadp.openshift.io/v1alpha1?timeout=32s
time="2023-06-23T11:05:23Z" level=info msg="Error getting resources kubeflow-anyuid-istio: the server could not find the requested resource "
time="2023-06-23T11:05:23Z" level=info msg="Error getting resources kubeflow-anyuid-kubeflow: the server could not find the requested resource "
time="2023-06-23T11:05:23Z" level=info msg="Error getting resources kubeflow-privileged-istio: the server could not find the requested resource "
time="2023-06-23T11:05:23Z" level=info msg="Error getting resources tekton-anyuid-kubeflow: the server could not find the requested resource "
time="2023-06-23T11:05:23Z" level=info msg="KfDef annotation added for resource scc-namespace-check.kubeflow"
time="2023-06-23T11:05:23Z" level=info msg="KfDef annotation added for resource kubeflow-anyuid-istio.kubeflow"
time="2023-06-23T11:05:23Z" level=info msg="KfDef annotation added for resource kubeflow-anyuid-kubeflow.kubeflow"
time="2023-06-23T11:05:23Z" level=info msg="KfDef annotation added for resource kubeflow-privileged-istio.kubeflow"
time="2023-06-23T11:05:23Z" level=info msg="KfDef annotation added for resource tekton-anyuid-kubeflow.kubeflow"
configmap/scc-namespace-check serverside-applied
securitycontextconstraints.security.openshift.io/kubeflow-anyuid-istio serverside-applied
securitycontextconstraints.security.openshift.io/kubeflow-anyuid-kubeflow serverside-applied
securitycontextconstraints.security.openshift.io/kubeflow-privileged-istio serverside-applied
securitycontextconstraints.security.openshift.io/tekton-anyuid-kubeflow serverside-applied
time="2023-06-23T11:05:31Z" level=info msg="Successfully applied application openshift-scc"
time="2023-06-23T11:05:31Z" level=info msg="Deploying application istio-stack"
time="2023-06-23T11:05:31Z" level=info msg="Inside the transform function"
I0623 11:05:33.183163 1 request.go:668] Waited for 1.196348328s due to client-side throttling, not priority and fairness, request: GET:https://172.30.0.1:443/apis/kfdef.apps.kubeflow.org/v1?timeout=32s
time="2023-06-23T11:05:40Z" level=warning msg="Error during custom transformerror mapping rest config no matches for kind \"CustomResourceDefinition\" in version \"apiextensions.k8s.io/v1beta1\""
time="2023-06-23T11:05:40Z" level=error msg="Error evaluating kustomization manifest for istio-stack: error mapping rest config no matches for kind \"CustomResourceDefinition\" in version \"apiextensions.k8s.io/v1beta1\""
```

**Comment by BlueCog** [comment]
Not sure if anyone is following this :D 

I've noted that the manifest example noted in the manual of the operator is outdated: https://raw.githubusercontent.com/kubeflow/manifests/v1.3-branch/distributions/kfdef/kfctl_openshift_v1.3.0.yaml

Were at 1.7.0 now.. Is the updated manifest hosted somewhere? It seems weird to me that the openshift ready operator is broken out of the box?

**Comment by AjayJagan** [comment]
Migrated this issue to JIRA: https://issues.redhat.com/browse/RHOAIENG-510, hence closing it here
