### ISSUE TITLE
Add ConsoleLink

### ISSUE THREAD

**Issue by VaishnaviHire** [opendatahub-io/opendatahub-operator#261]
Explore if ConsoleLink creation should be moved to `odh-dashboard` manifests or as part of DSCInitialization creation

Current Implementation - https://github.com/red-hat-data-services/odh-deployer/tree/main/consolelink

**Comment by zdtsw** [comment]
@VaishnaviHire can I be assigned for this issue?

**Comment by VaishnaviHire** [comment]
@zdtsw Updated description as well

**Comment by VaishnaviHire** [comment]
@zdtsw This probably can be included into [odh-dashboard](https://github.com/opendatahub-io/odh-manifests/tree/master/odh-dashboard) manifests ?

**Comment by zdtsw** [comment]
> @zdtsw This probably can be included into [odh-dashboard](https://github.com/opendatahub-io/odh-manifests/tree/master/odh-dashboard) manifests ?

My thoughts for this issue is 
store the `consolelink.yaml` into `odh-manifests/odh-dashboard/base` on feature-rearchitecture branch
create a new file in `controllers/dscinitialization` add apply logic to it,  calling `ReplaceStringsInFile` to replace `$rhods-dashbaord-url `in consolelink.yaml

does this sound reasonable?

**Comment by zdtsw** [comment]
i am now wondering if consolelink should be applied to ODH upstream or only required for downstream e.g RHODS ? 
e.g https://github.com/opendatahub-io/odh-dashboard/blob/b1de206682aba8edc36cee344a0832af2afd05af/frontend/src/app/AppLauncher.tsx#L27 is explicitly checking for "rhodslink"

or maybe the logic add into new operator should be checking if it is  `deploy.OpenDataHub` or not before apply CR
