### ISSUE TITLE
SPIKE testing folder already in opendatahub-operator

### ISSUE THREAD

**Issue by nakfour** [opendatahub-io/opendatahub-operator#27]

**Comment by crobby** [comment]
First glance, it looks like there are no automated tests of any sort for the operator.  The testing bits that are there seem to revolve around kfctl itself.  There is a bunch of jsonnet/libsonnet files that look like they set up a bunch of variables.and functions.  I'm not finding any docs on these tests or how to run them or anything of that sort.

Also, there is a py/kubeflow/testing directory that contains a bunch of python-based tests.  These are what get ran inside the tests that are triggered for each PR and nightly builds.

The kfctl_e2e_workflow.py file has some instructions on how you might be able to run these tests, but they talk about "e2e_tool.py" being used to do that and I can't find e2e_tool.py anywhere in this repo, so there's a chance that the doc is out of date.  I'll keep trying to track it down.

The operator.md file has a section called "Testing Watcher and Reconciler", but that section simply describes a set of manual tests that you can run (kubectl commands to run and then observe the results manually).  It wouldn't be too hard to take that philosophy and create a set of tests similar to what we have in odh-manifests and even extend that to give a more thorough e2e test.

**Comment by crobby** [comment]
Ok, upon further review, the e2e_tool.py does exist, it just lives here:  https://github.com/kubeflow/testing/blob/master/py/kubeflow/testing/e2e_tool.py  (in the kubeflow/testing repo).  There is a README there, so I will look around there to see if that gets us anywhere useful.

**Comment by crobby** [comment]
Yeah, looking like the e2e_tool is also focused around creating argo workflows that run the tests.

So, I don't think we want to rely on Argo Workflows for our purposes, so I will see if I can find a way to run the actual tests without the Argo Workflow baggage.

We may need our own wrapper/set of wrappers should we ever want to incorporate these tests into our own Tekton/ocp pipelines.
