### ISSUE TITLE
Update alm example to exclude any user inputs

### ISSUE THREAD

**Issue by VaishnaviHire** [opendatahub-io/opendatahub-operator#296]
One of the `alm` examples provided in the CSV include enabling/disabling components [explicitly](https://github.com/opendatahub-io/opendatahub-operator/blob/feature-rearchitecture/bundle/manifests/opendatahub-operator.clusterserviceversion.yaml#L99) . This overrides the profile settings and may cause confusion if used as default instance.

- Include core/none profile as default instance
- Provide other combination as examples or samples separately

**Comment by zdtsw** [comment]
my thoughts:  we can use `.metadata.annotations to  add something like for other combination as examples
```
extra-examples:  |
   - profile: training
     components:
        dashboard: 
            enabled: false
        datasciencepipelines:{},
        modelmeshserving: {},
        workbenches:{}
   - profile: core
      components:
        dashboard: 
            enabled: false
        datasciencepipelines:{},
        modelmeshserving: {},
        workbenches:
             enabled: false
```

how you think @VaishnaviHire ?

**Comment by VaishnaviHire** [comment]
No longer required
