### ISSUE TITLE
Add CI tests for ODH CSV releases in deploy/olm-catalog/opendatahub

### ISSUE THREAD

**Issue by LaVLaS** [opendatahub-io/opendatahub-operator#30]
As part of the release process we should look into adding CI tests for ODH releases that will verify the files added are valid and correct.

Community Operators [CI tests](https://github.com/operator-framework/community-operators#test-your-operator-before-submitting-a-pr)

**Comment by nakfour** [comment]
we are migrating to https://issues.redhat.com/projects/ODH/summary can you please move all your open issues there.
