### ISSUE TITLE
while creation second ` Create DataScienceCluster`  there should be a warning/nortification 

### ISSUE THREAD

**Issue by mwaykole** [opendatahub-io/opendatahub-operator#328]
**Describe the bug**
The initial creation of the DataScienceClusters will function properly. However, subsequent attempts to create new DataScienceClusters without deleting the first cluster will result in a wait until the first DataScienceClusters is deleted. In order to alert the user about this limitation, it should display a warning or notification, or alternatively, disable the creation button by greying it out. This will ensure that users are aware of the situation.

**To Reproduce**
1. install operator 
2. go to  DataScienceClusters  then click  Create DataScienceCluster
3.  select component any component and name it example1
4. repeat 3rd  and 4th step with second name as  example2

https://github.com/opendatahub-io/opendatahub-operator/assets/44530572/35ddc042-db97-479f-af3f-8138a01e3b58

**Comment by zdtsw** [comment]
I think you should see error message in pod's log, 
something like `only one instance of DataScienceCluster object is allowed. Update existing instance on namespace opendatahub and example2` right?

**Comment by etirelli** [comment]
Fixed here: https://github.com/opendatahub-io/opendatahub-operator/commit/a0ac271a83c9dfe392c6ebb2d4c6badb0dfae6f6
