### ISSUE TITLE
Explore Getting component Manifests directly from the component repos

### ISSUE THREAD

**Issue by VaishnaviHire** [opendatahub-io/opendatahub-operator#338]
**Is your feature request related to a problem? Please describe.**
Currently the operator pulls manifests from `odh-manifest` repo. Since it is just a collection of component manifest, explore ways to update Operator build to include component manifests directly from respective repos

Further we can also update DSC CR to include remote manifest uri only for `dev` mode.

- [x] #424
- [x] #425
- [x] [Add ADR with proposal](https://github.com/opendatahub-io/architecture-decision-records/pull/16)
- [x] [Document release process for updated manifest integration](https://github.com/opendatahub-io/opendatahub-operator/wiki/3.-Using-Operator-in-Dev-Mode)

**Comment by zdtsw** [comment]
one possibility is:

component team own part of the odh-manifests
with such yaml files under their git repo `config/manifest` folder


in operator, we have a mapping file (like the upstream_midstream.yaml)
with source component git repo url and point to `config/manifests` folder

during operator image build time, COPY/ADD these filed from every git repo listed in mapping file.
