### ISSUE TITLE
Jupyter tile always missing from the `Enabled` section of the Dashboard

### ISSUE THREAD

**Issue by lugi0** [opendatahub-io/opendatahub-operator#365]
**Describe the bug**
The Jupyter tile is always missing from the Enabled section of the dashboard, but it is present in the Explore section. Either we need to remove it completely or we need to make it available for use when the workbenches component is enabled

**To Reproduce**
1. Go to Dashboard
2. Click on Applications > Enabled
4. See `No components found` error

**Expected behavior**
The Jupyter tile should be available when the workbenches component is enabled, or it should be removed entirely (so from Applications > Explore as well)

**Screenshots**
![image](https://github.com/opendatahub-io/opendatahub-operator/assets/82518733/0d1b0f1d-0934-4a0f-b3ce-3af7f7f309d8)

**Additional context**

**Comment by VaishnaviHire** [comment]
/cc @andrewballantyne 

This should be related to https://github.com/opendatahub-io/odh-dashboard/issues/1510

**Comment by andrewballantyne** [comment]
Should be resolved in https://github.com/opendatahub-io/odh-dashboard/pull/1592

**Comment by VaishnaviHire** [comment]
Fixed as part of above mentioned PR
<img width="1784" alt="Screenshot 2023-08-01 at 3 18 08 PM" src="https://github.com/opendatahub-io/opendatahub-operator/assets/17230536/b5d5316b-5a66-425d-a713-1877c26200d4">
