### ISSUE TITLE
Add Logger for operator

### ISSUE THREAD

**Issue by VaishnaviHire** [opendatahub-io/opendatahub-operator#368]
Since all the manifests do not comply with v5 of kustomize, we have deprecation warnings for kustomize manifests.

Remove those warning logs and introduce logger that can be display just Info/Error messages and has a debug mode. Explore implementing log verbosity levels(`r.Log.V()`). 

Longterm , we need components to update there manifests to be compliant with kustomize v5

**Comment by zdtsw** [comment]
remove "remove warning logs from operator" from title. since this can only be done when manifests syntax are migrated to v5.

**Comment by AjayJagan** [comment]
Migrated to JIRA: https://issues.redhat.com/browse/RHOAIENG-504, hence closing it here.
