### ISSUE TITLE
Spark-operator rolebinding when deploying in multiple namespaces.

### ISSUE THREAD

**Issue by guimou** [opendatahub-io/opendatahub-operator#37]
After updating OpenShift to 4.3.25, the Spark Operator is CrashLoopBackOff-ing.
Error is:
```Failed to start application: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://172.30.0.1/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. customresourcedefinitions.apiextensions.k8s.io is forbidden: User "system:serviceaccount:odh:spark-operator" cannot list resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope.```
So somehow the spark-operator SA lost some privileges.
Is it due to the update itself (never happened before during an update) or to the OCP version?
The spark-operator SA, role and role-binding are still present though...

**Comment by guimou** [comment]
OK, wrong diagnosis. In fact ODH is installed in different namespaces (test, staging, production). There were multiple uninstall/reinstall (not sure if it's linked though), but current state was that the RoleBinding for spark-operator was only using one of the service accounts in a specific namespace. Will change the title and see if it's related to the uninstalls/installs, or to the way it's deployed.

**Comment by griffincollege** [comment]
After a cluster upgrade or restart, I am seeing this issue as well, however I am only deploying in a single namespace.

**Comment by nakfour** [comment]
@guimou @griffincollege which version of ODH are you installing? Is this a manual install or from the operator?

Juana

**Comment by guimou** [comment]
0.6.1 from the operator.

**Comment by guimou** [comment]
Other useful info: I manually added the SAs from the other namespaces to the RoleBinding. 
But after some time it reverted to only one account from one namespace. So pointing to the operator just replacing the account, not adding it with a new deployment. Did not have time to look to the manifest yet, but I put 2$ on this... Will do later today if I have time.

**Comment by griffincollege** [comment]
@nakfour Same for me, using this from the Operator as well.
