### ISSUE TITLE
Autogeneration of PRs for merging

### ISSUE THREAD

**Issue by jkoehler-redhat** [opendatahub-io/opendatahub-operator#371]
**Is your feature request related to a problem? Please describe.**
Need to better autgenerate what PRs are included between versions

**Describe the solution you'd like**
See:
https://github.com/HumairAK/gh-to-jira
https://github.com/opendatahub-io/data-science-pipelines-operator/pull/213

**Comment by ajaypratap003** [comment]
@jkoehler-redhat As discussion is going on about automation `gh-to-jira`. Should we keep this issue on hold for time being or close ?

**Comment by ajaypratap003** [comment]
As discussed with team, closing this issue as devops team is working on `gh-to-jira` automation.
