### ISSUE TITLE
Support multiple configurations of ODH Deployments

### ISSUE THREAD

**Issue by VaishnaviHire** [opendatahub-io/opendatahub-operator#396]
The current version of operator supports single version of ODH configuration(platform) and deployments at any given time.

Explore approaches to support multiple versions of ODH Deployments with separate configurations(odh vs supported) at a given time in a cluster

**Possible Approaches**

Approach 1:
1. Add `previewSupported: enabled` field in DSC cluster
2. When users enable it, create another DSCInitialization(CR used for initial setup) instance with `supported` namespaces and manifests
3. Set platform explicitly to selfmanaged(`supported`). 
4. Results should be separate namespaces with 2 versions of controllers
5. Possible risks: Components with cluster-wide resources should be tested for conflicts, updates in cluster-wide resources

Approach 2:
1. Multiple versions of operator(tbd)

**Comment by AjayJagan** [comment]
Migrated to JIRA: https://issues.redhat.com/browse/RHOAIENG-505, hence closing this issue
