### ISSUE TITLE
Typeo in datasciencecluster example in the bundle

### ISSUE THREAD

**Issue by tedhtchang** [opendatahub-io/opendatahub-operator#404]
**Describe the bug**
This [distributedworkloads](https://github.com/tedhtchang/opendatahub-operator/blob/23299563e8e92e1c057fdf1cfac96cc8e6a7a3ff/bundle/manifests/opendatahub-operator.clusterserviceversion.yaml#L99C16-L99C36) should have capitalized `w` otherwise would it not deploy distributedWorkloads from the OpenShift console.

**To Reproduce**
Steps to reproduce the behavior from Openshift console UI:
1. Install Codeflare operator and opendata hub operator
1. Deploy the datasciencecluster example from UI
![image](https://github.com/opendatahub-io/opendatahub-operator/assets/7155778/3c987372-e1f2-4b09-b96b-cc085389845f)
1. set enabled: true for the distributedworkload and save
![image](https://github.com/opendatahub-io/opendatahub-operator/assets/7155778/dad7ec63-23d9-464c-94f2-641c791333f0)

1. Observed the  `distributedWorkloads.enabled: false` still false and codeflare-stack and ray operator are not installed.
![image](https://github.com/opendatahub-io/opendatahub-operator/assets/7155778/62c33831-f569-44d7-9bfc-a102be907b09)

**Expected behavior**
After save, distributedWorkloads.enabled should be true and codeflare-stack(mcad, instascale, etc) and ray-operator should be installed.

cc @anishasthana @jbusche

**Comment by anishasthana** [comment]
This may not be relevant for much longer as they are splitting DW into CodeFlare and Ray components. @etirelli fyi

**Comment by tedhtchang** [comment]
That's interesting. I would think just adding Ray and mcad/instascale. Deploying CodeFlare without Ray would make it partially functional.

**Comment by zdtsw** [comment]
@anishasthana is correct, the coming release for new operator has "codeflare" and "ray" components to replace the current "distributedworkloads"

**Comment by VaishnaviHire** [comment]
Closing this, since we have the change for introducing `codeflare` and `ray` merged in - https://github.com/opendatahub-io/opendatahub-operator/pull/377
