### ISSUE TITLE
Update Dockerfile to include component manifests

### ISSUE THREAD

**Issue by VaishnaviHire** [opendatahub-io/opendatahub-operator#424]
checklist for left components in ODH:
- [modelmesh](https://github.com/opendatahub-io/modelmesh/issues/31)
- [kserve](https://github.com/opendatahub-io/kserve/issues/72)
upstream
checklist for downstream:
- [Kserve](https://github.com/opendatahub-io/kserve/issues/72)
- [modelmesh](https://github.com/opendatahub-io/modelmesh/issues/31)
- [dashboard](https://github.com/red-hat-data-services/odh-dashboard/issues/296)
- [notebook](https://github.com/opendatahub-io/notebooks/issues/185)
- [DW] might change where the manifests from if deprecate distributed-workflow repo

operator:
- [x] https://github.com/opendatahub-io/opendatahub-operator/pull/431
- [ ] https://github.com/red-hat-data-services/rhods-operator/pull/43
- [x] midstram https://gitlab.cee.redhat.com/data-hub/rhods-cpaas-midstream/-/merge_requests/1067
- [ ] live-builder
- [x] https://github.com/opendatahub-io/opendatahub-operator/pull/544

**Comment by zdtsw** [comment]
to catch the offline conversation:

each component has their manifests already in their repo.
this issue is to fetch these manifests from different git repo (instead of from one central odh-manifests) and place them in the correct local in the final image, e.g /opt/manifests/<componetn>/...

will start with "main" branch from these git repo and check with each component which branch will suit best and updated if required.

**Comment by zdtsw** [comment]
list of what we are using from odh-manifests as 

- [ ] codeflare: https://github.com/opendatahub-io/odh-manifests/tree/master/codeflare-stack
- [ ] dsp: https://github.com/opendatahub-io/odh-manifests/tree/master/data-science-pipelines-operator
- [ ] kserve: https://github.com/opendatahub-io/odh-manifests/tree/master/kserve
- [ ] modelmesh: https://github.com/opendatahub-io/odh-manifests/tree/master/model-mesh
- [ ] monitoring1: https://github.com/opendatahub-io/odh-manifests/tree/master/modelmesh-monitoring/base
- [ ] monitoring2: https://github.com/opendatahub-io/odh-manifests/tree/master/prometheus
- [ ] workbench1: https://github.com/opendatahub-io/odh-manifests/tree/master/notebook-images
- [ ] workbench2: https://github.com/opendatahub-io/odh-manifests/tree/master/odh-notebook-controller
- [ ] dashboard: https://github.com/opendatahub-io/odh-manifests/tree/master/odh-dashboard
- [ ] ray: https://github.com/opendatahub-io/odh-manifests/tree/master/ray

special cases for downstream:
- [ ] dashboard: https://github.com/red-hat-data-services/odh-manifests/tree/master/partners/anaconda/base

**Comment by zdtsw** [comment]
@VedantMahabaleshwarkar / @Jooho  Could you point to me where manifests in https://github.com/opendatahub-io/odh-manifests/tree/master/model-mesh  came from?

**Comment by zdtsw** [comment]
@harshad16 could you take a look  how to make the nb/nbc part  work? 
```
workbench1: https://github.com/opendatahub-io/odh-manifests/tree/master/notebook-images > where this one maps from
 workbench2: https://github.com/opendatahub-io/odh-manifests/tree/master/odh-notebook-controller > where this one maps from
```

**Comment by zdtsw** [comment]
we still would need a `params.env` file placed in https://github.com/opendatahub-io/kserve/tree/master/config/overlays , something simliar to https://github.com/red-hat-data-services/odh-manifests/blob/master/kserve/base/params.env
@danielezonca

**Comment by harshad16** [comment]
@zdtsw Apologies for the delay.
We have finally included the manifests in the repos.
Can you please update the above comment with these links:


- workbench1(notebook-images) > https://github.com/opendatahub-io/notebooks/tree/main/manifests 
Reference: https://github.com/opendatahub-io/notebooks/pull/186
- workbench2 (odh-notebook-controller) > https://github.com/opendatahub-io/kubeflow/tree/v1.7-branch/components
Reference: https://github.com/opendatahub-io/kubeflow/pull/173

These contain the base folder for Kustomize to execute. 
Thank for the patience and support.

**Comment by zdtsw** [comment]
> @zdtsw Apologies for the delay. We have finally included the manifests in the repos. Can you please update the above comment with these links:
> 
> * workbench1(notebook-images) > https://github.com/opendatahub-io/notebooks/tree/main/manifests
>   Reference: [Include notebook imagestream manifests to notebook repos notebooks#186](https://github.com/opendatahub-io/notebooks/pull/186)
> * workbench2 (odh-notebook-controller) > https://github.com/opendatahub-io/kubeflow/tree/v1.7-branch/components
>   Reference: [Include odh notebook-controller manifests to the repos kubeflow#173](https://github.com/opendatahub-io/kubeflow/pull/173)
> 
> These contain the base folder for Kustomize to execute. Thank for the patience and support.

thanks @harshad16 i have commited your suggestion in ADR and will include nbc change as well in operator

**Comment by Jooho** [comment]
@zdtsw the manifests are from modelmesh-serving/opendatahub/odh-manifests/model-mesh_stable for now.
