### ISSUE TITLE
DSC should report error in conditions for missing pre-reqs

### ISSUE THREAD

**Issue by strangiato** [opendatahub-io/opendatahub-operator#427]
**Is your feature request related to a problem? Please describe.**
When installing components via the DSC, the DSC should report issues with missing pre-reqs such as openshift-pipelines for data-science-pipelines.

**Describe the solution you'd like**
For components that require pre-reqs such as DSP or distrubtedWorkloads (Code Flare Operator), the DSC should report an error in the conditions and flag the DCS as degraded:

```
    - lastHeartbeatTime: '2023-08-08T22:09:33Z'
      lastTransitionTime: '2023-08-08T22:09:33Z'
      message: Component requires OpenShift Pipelines Operator
      reason: MissingPreReqs
      status: 'False'
      type: data-science-pipelines-operatorReady
    - lastHeartbeatTime: '2023-08-08T22:09:53Z'
      lastTransitionTime: '2023-08-08T22:09:12Z'
      message: Component requires OpenShift Pipelines Operator
      reason: MissingPreReqs
      status: 'True'
      type: Degraded
```

**Describe alternatives you've considered**

**Additional context**
DSP and distrubtedWorkloads require additional operators to be installed to function but there may be additional pre-reqs that we may want to consider for other components.

Providing this feedback on the DSC can help to get this information to platform admins faster instead of having to rely on the warning provided by the dashboard today.

It may also be worth setting the `Phase` into an error state as well.

**Comment by VaishnaviHire** [comment]
This issue has been resolved by #385 #497
