### ISSUE TITLE
Track changes for automatic upgrade path

### ISSUE THREAD

**Issue by VaishnaviHire** [opendatahub-io/opendatahub-operator#461]
Seamlessly upgrade operator from v1.x to v2.x for a given applications namespace.

- [ ] Verify resource update works when deployed with v2.
- [ ] #586
- [ ] #587
        - Verify network policies are not redundant
        - Verify monitoring resources are not redundant
- [ ] Test bundle update

**Comment by lugi0** [comment]
Setting this to failed verification in Jira due to the issue in #587
