### ISSUE TITLE
RHODS dashboard does not work when deploying in a single namespace

### ISSUE THREAD

**Issue by lugi0** [opendatahub-io/opendatahub-operator#462]
**Describe the bug**
When deploying RHODS in a single namespace, the RHODS dashboard will not work even though all dashboard pods are up and running. 

**To Reproduce**
1. Install Operator v2 with flag
2. Create DSCI CR and point at a single namespace
3. Create DSC CR and enable components (at least dashboard)
4. Try navigating to the rhods dashboard URL

**Expected behavior**
RHODS dashboard is accessible

**Screenshots**
![image](https://github.com/opendatahub-io/opendatahub-operator/assets/82518733/3f38e19b-646c-47e6-911c-8d51891a63ea)

**Additional context**
Using 1.32 RC1

**Comment by zdtsw** [comment]
@lugi0 can this issue be closed?

**Comment by zdtsw** [comment]
close this issue as have been verified in the later build, fyi @lugi0
