### ISSUE TITLE
In RHODS 1.32 RC3, OAuth container always fails for dashboard route

### ISSUE THREAD

**Issue by lugi0** [opendatahub-io/opendatahub-operator#480]
**Describe the bug**
In the 1.32 RC3, the RHODS dashboard is not accessible due to an internal server error in the OAuth containers
```
2023/08/25 11:58:10 provider.go:587: Performing OAuth discovery against https://172.30.0.1/.well-known/oauth-authorization-server
2023/08/25 11:58:10 provider.go:627: 200 GET https://172.30.0.1/.well-known/oauth-authorization-server {
"issuer": "https://oauth-openshift.apps.ods-qe-01.rhods.ccitredhat.com",
"authorization_endpoint": "https://oauth-openshift.apps.ods-qe-01.rhods.ccitredhat.com/oauth/authorize",
"token_endpoint": "https://oauth-openshift.apps.ods-qe-01.rhods.ccitredhat.com/oauth/token",
"scopes_supported": [
"user:check-access",
"user:full",
"user:info",
"user:list-projects",
"user:list-scoped-projects"
],
"response_types_supported": [
"code",
"token"
],
"grant_types_supported": [
"authorization_code",
"implicit"
],
"code_challenge_methods_supported": [
"plain",
"S256"
]
}
2023/08/25 11:58:10 oauthproxy.go:656: error redeeming code (client:10.131.0.1:34804): got 400 from "https://oauth-openshift.apps.ods-qe-01.rhods.ccitredhat.com/oauth/token" {"error":"unauthorized_client","error_description":"The client is not authorized to request a token using this method."}
2023/08/25 11:58:10 oauthproxy.go:445: ErrorPage 500 Internal Error Internal Error
```

**To Reproduce**
1. Install RC3
2. Go to RHODS dashboard
3. Try logging in
4. See 500 error page

**Expected behavior**
Users can log into the Dashboard

**Screenshots**
![image](https://github.com/opendatahub-io/opendatahub-operator/assets/82518733/e41762fb-ec2e-4b1c-a53b-af5ddc956bed)

**Additional context**

**Comment by lugi0** [comment]
Have not been able to reproduce this on other clusters, it might be a one-off issue of a single cluster

**Comment by zdtsw** [comment]
I still believe https://github.com/red-hat-data-services/odh-manifests/pull/460 is needed for 1.32

the change was in the 1.31 and this PR is applying it for master branch before 1.32 was branched out.
unfortunately, it did not get merged into master thus not on 1.32
@lugi0 @lucferbux

**Comment by lucferbux** [comment]
Yup, that's right, I raised the PR, but I'm not sure who can merge that, I can prepare the cherry-pick for 1.32
cc @andrewballantyne @zdtsw @lugi0

**Comment by zdtsw** [comment]
ref: https://issues.redhat.com/browse/RHODS-11469

**Comment by zdtsw** [comment]
close issue as it has been verified with fix, fyi @lugi0 @lucferbux
