### ISSUE TITLE
kserve-controller-manager doesn't have enough CPU to run at scale

### ISSUE THREAD

**Issue by kpouget** [opendatahub-io/opendatahub-operator#499]
**Describe the bug**
While running the KServe scale test, we observed that the `kserve-controller-manager` is unable to answer the queries in due time:
```
2023-08-30 10:33:43,425 p=1878 u=psap-ci-runner n=ansible | <stderr> Error from server (InternalError): 
- error when creating "/mnt/logs/004__watsonx_serving__deploy_model/src/inference_service.yaml": 
- Internal error occurred: failed calling webhook "inferenceservice.kserve-webhook-server.defaulter": 
failed to call webhook: 
- Post "[https://kserve-webhook-server-service.redhat-ods-applications.svc:443/mutate-serving-kserve-io-v1beta1-inferenceservice?timeout=10s](https://kserve-webhook-server-service.redhat-ods-applications.svc/mutate-serving-kserve-io-v1beta1-inferenceservice?timeout=10s)": 
- context deadline exceeded
```

**To Reproduce**
1. Deploy a large number of models (300) in a short timeframe
2. Query the `InferenceService` objects regularly
3. Observe that the KServe webhook is unable to answer the requests 

**Expected behavior**
The KServe webhook is always able to answer the requests

**Additional context**
The issue likely comes from the low amount of CPU limit given to the `kserve-controller-manager`:
```
                        "resources": {
                            "limits": {
                                "cpu": "100m",
                                "memory": "300Mi"
                            },
                            "requests": {
                                "cpu": "100m",
                                "memory": "200Mi"
                            }
                        },
```

**Workaround**
I ran the same scale test with 
1. the RHODS operator turned off
2. the test passed with the CPU and memory limit increased to these values:
```
    rhods.operator.customize.kserve.cpu: 500m
    rhods.operator.customize.kserve.memory: 500Mi
```
```python
        run.run(f"oc get deploy/kserve-controller-manager -n redhat-ods-applications -ojson "
                f"| jq --arg mem '{mem}' --arg cpu '{cpu}' '.spec.template.spec.containers[0].resources.limits.cpu = $cpu | .spec.template.spec.containers[0].resources.limits.memory = $mem' "
                f"| oc apply -f-")
```

**Comment by zdtsw** [comment]
i cannot transfer this issue, but it should be reported in https://github.com/opendatahub-io/kserve for triage

**Comment by kpouget** [comment]
@zdtsw , could you show me how the ODH operator knows what to reconciliate when `DataScienceCluster.spec.kserve` is in `Managed` mode? I'd like to understand how the "not-generic" values are defined

in [this file](https://github.com/opendatahub-io/kserve/blob/master/charts/kserve-resources/templates/deployment.yaml#L5) I don't see memory request being defined, as so far I couldn't find it anywhere else :/

@Jooho maybe you know? (IIRC, you suggested to open this ticket in this repo)

**Comment by zdtsw** [comment]
the main logic in operator is only to apply what is defined in kserve manifests, specificly https://github.com/opendatahub-io/odh-manifests/blob/master/kserve/base/kustomization.yaml and then https://github.com/opendatahub-io/odh-manifests/blob/master/odh-model-controller/base/kustomization.yaml
the first file is originally generated from kserve git repo by https://github.com/opendatahub-io/odh-manifests/blob/master/kserve/hack/build-kserve-manifests.sh, which i believe is set in https://github.com/opendatahub-io/odh-manifests/blob/master/kserve/kserve-built/kserve-built.yaml#L18838

**Comment by kpouget** [comment]
ok, thanks, I found it. In this repo, the resource request is currently defined [there](https://github.com/opendatahub-io/odh-manifests/blame/master/kserve/kserve-built/kserve-built.yaml#L18840):
```
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 200Mi
```
and the original definition comes from `opendatahub-io/kserve`, in [this file](https://github.com/opendatahub-io/kserve/blob/master/config/default/manager_resources_patch.yaml):
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kserve-controller-manager
  namespace: kserve
spec:
  template:
    spec:
      containers:
      - name: manager
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
```
I'll clone this ticket in the `opendatahub-io/kserve` repo, and we'll keep this one open as the `kserve-built.yaml` file will have to be regenerated once KServe has been updated.

**Comment by zdtsw** [comment]
@kpouget do you think this is a blocker for KServe?
btw, re-generated kserve-built.yaml by the script is not done by platform team, rather by serving team when they want to release new version of KServe.

**Comment by kpouget** [comment]
> @kpouget do you think this is a blocker for KServe?
no, not for RHODS 1.32, but should be done for 1.33

> btw, re-generated kserve-built.yaml by the script is not done by platform team, rather by serving team when they want to release new version of KServe.

ack, do you think we should close this ticket then? I was thinking it should be closed then this repo has been updated, but you decide!

**Comment by zdtsw** [comment]
I can close it, as long as you feel fine with it
