### ISSUE TITLE
Add support for IBM Power architecture (ppc64le)

### ISSUE THREAD

**Issue by mgiessing** [opendatahub-io/opendatahub-operator#50]
Hi,

is it possible to add support for IBM Power Platform (ppc64le)?
I have an OpenShift 4 deployment but I'll get an error which indicates that Power Architecture is not supported yet:

```
[root@edb-fc33-bastion ~]# oc logs opendatahub-operator-95c7977d5-sphrn
standard_init_linux.go:211: exec user process caused "exec format error"
```

Thanks a lot!

**Comment by vpavlin** [comment]
Hi, sorry, we started this effort to enable ppc64le, but since we did not have access to a cluster on that architecture and other priorities came up, we dropped it.

It would be great to come back to this in the future, but I don't see that happening anytime soon.
