### ISSUE TITLE
Add support for Presto in ODH

### ISSUE THREAD

**Issue by shgriffi** [opendatahub-io/opendatahub-operator#51]
There have been questions in the ODH community regarding support for Presto.  There are a number of use cases that Presto can help with in Open Data Hub.

1. Distributed query engine
2. Supports federated queries across different data sources and databases
3. Supports RBAC with additional components such as Ranger or Sentry (https://docs.starburstdata.com/latest/security/rbac.html)

Use cases for Presto in ODH
1. Hue integrated with Presto for ad-hoc queries of data in the object storage data lake
2. Superset integrated with Presto for data exploration

Starburst has an enterprise Presto operator on OpenShift (https://marketplace.redhat.com/en-us/products/starburst-presto-enterprise).  If there is a license that allows free use of Presto in Open Data Hub, it would be a good addition to the architecture for ad-hoc query capabilities across multiple data sources.

**Comment by nakfour** [comment]
Migrating comments from gitlab: https://gitlab.com/opendatahub/opendatahub-operator/-/issues/120

----------------
Maulik Shah @maulikjs · 4 months ago
Developer
Hey @jnakfour @pdmack @vpavlin @shgriffi Did we decide on how we want to go ahead with this?

The starburstdata presto operator is closed source and therefore in the free version, there is a cap on memory and cores we can use. One solution could be we could abstract out those parameters so it only runs at a specific resource limit. Or we can comment in the CR that for free version they shouldnt change the 2 flags and if they have a license (a secret in the namespace) they can bump that up.

What are your thoughts?
-------------------------

**Comment by shgriffi** [comment]
The limitations of the license seem to be listed here https://docs.starburstdata.com/latest/kubernetes/overview.html#license.  We will need confirmation from Starburst if that is the case.  Could we get someone from Starburst to contribute their operator to ODH?

**Comment by hbhanawat** [comment]
Falarica Analytics has open sourced its Kubernetes Operator for Presto yesterday. The operator is production ready with features like autoscaling, https support, secrets for catalogs, self healing, support for property files (authentication, resource groups etc). Operator works for both PrestoDB and PrestoSQL.

https://github.com/falarica/steerd-presto-operator

We look forward to work with the OpenDataHub community to make this more suitable for adhoc analytics use cases.

**Comment by nakfour** [comment]
We added Trino component to ODH.
