### ISSUE TITLE
Extend e2e tests to include all components

### ISSUE THREAD

**Issue by VaishnaviHire** [opendatahub-io/opendatahub-operator#512]
The e2e tests currently enables only couple of components. Update the tests to enable all components to test the entire ODH deployment

Creation of DSC Instance: https://github.com/opendatahub-io/opendatahub-operator/blob/main/tests/e2e/helper_test.go#L55C6-L55C22

**Comment by ykaliuta** [comment]
Is it about just changing `Removed` to `Managed`? Because  as far as I see https://github.com/opendatahub-io/opendatahub-operator/blob/main/tests/e2e/dsc_creation_test.go#L90 already checks creation. Or there is some more functionality in mind to add?

**Comment by VaishnaviHire** [comment]
- Since now we have Modelmesh and KServe compatible to each other, we should set modelmesh to `Managed`
- Codeflare needs to be set to managed as well. This requires, installing codeflare operator.

- We should also set DSCI `Servicemesh` fields to managed. This requires users to install `Servicemesh` and `Serverless` operators

**Comment by sutaakar** [comment]
> Codeflare needs to be set to Managed as well. This requires, installing codeflare operator.

For enabling CodeFlare in ODH there is no operator installation needed. CodeFlare can be installed without any additional dependencies.

**Comment by AjayJagan** [comment]
Migrated to JIRA: https://issues.redhat.com/browse/RHOAIENG-489, hence closing it here.
