### ISSUE TITLE
Create Unit Tests for Monitoring Functions

### ISSUE THREAD

**Issue by VaishnaviHire** [opendatahub-io/opendatahub-operator#517]
We need to ensure that our monitoring functions have adequate test coverage. Create Ginkgo unit tests to cover the below functions:

- [ ] Test **configurePrometheus** Function
    - Ensure that the function retrieves the correct alertmanagerRoute.
    - Validate successful retrieval of the alertmanagerConfigMap.
    - Test the correct reading of alertmanager.yml data from the ConfigMap.
    - Validate deployment of the Prometheus ConfigMap and its subsequent retrieval.
    - Test the reading of prometheus.yaml data from the Prometheus ConfigMap.
    - Ensure the correct injection of data into the prometheus.yaml and prometheus-viewer-rolebinding.yaml manifests.
    - Validate deployment of Prometheus manifests.
    - Test the successful creation of the prometheus-proxy secret.

- [ ] Test **configureAlertManager** Function
    - Validate the retrieval of secrets: redhat-rhods-deadmanssnitch, redhat-rhods-pagerduty, redhat-rhods-smtp, and addon-managed-odh-parameters.
    - Ensure the correct injection of data into the alertmanager-configs.yaml manifest.
    - Test the deployment of the alertmanager manifests.
    - Ensure the successful creation of the alertmanager-proxy secret.

- [ ] Test **configureBlackboxExporter** Function
    - Validate the conditions that determine which set of blackbox exporter manifests are deployed (internal vs. external).
    - Test deployment of the selected blackbox exporter manifests.

- [ ] Test **configureManagedMonitoring** Function
    - Test the successful configuration of Alertmanager, Prometheus, and Blackbox Exporter.

- [ ] Test **createMonitoringProxySecret** Function
    - Validate the successful generation of a random hex session secret.
    - Test the creation or retrieval of the monitoring proxy secret.

- [ ] Test **replaceInAlertManagerConfigmap** Function
     - Validate the correct replacement of variables in the AlertManager ConfigMap.

- [ ] Test **getMonitoringData** Function
     - Validate the correct SHA-256 hashing and Base64 encoding of the input data.

- [ ] Test **configureCommonMonitoring** Function
     - Test the deployment of the segment-io manifests.

**Acceptance Criteria:**
- All tests should pass without errors.
- Mock external dependencies to avoid side-effects.
- Ensure coverage of edge cases and error conditions.

**Comment by AjayJagan** [comment]
JIRA issue: https://issues.redhat.com/browse/RHOAIENG-448
