### ISSUE TITLE
CSV upload in Superset fails with  [Errno 13] Permission denied: '/opt/app-root/lib/python3.6/site-packages/superset/app' 

### ISSUE THREAD

**Issue by romeokienzler** [opendatahub-io/opendatahub-operator#52]
Configured the SQLite example data source to allow for CSV upload but upon upload I get:

 [Errno 13] Permission denied: '/opt/app-root/lib/python3.6/site-packages/superset/app'

**Comment by nakfour** [comment]
@romeokienzler yes we have an open issue for this https://github.com/opendatahub-io/odh-manifests/issues/70

**Comment by romeokienzler** [comment]
great thanks a lot @nakfour !
