### ISSUE TITLE
Add support for "acceleratorprofiles" from dashboard

### ISSUE THREAD

**Issue by zdtsw** [opendatahub-io/opendatahub-operator#525]
**Is your feature request related to a problem? Please describe.**
Dashboard has introduced a new CRD `acceleratorprofiles` we will need to integrate it into operator

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
[Add any other context or screenshots about the feature request here.](https://github.com/opendatahub-io/odh-dashboard/blob/incubation/manifests/crd/acceleratorprofiles.opendatahub.io.crd.yaml)

**Comment by VaishnaviHire** [comment]
Closing this, as it is no longer relevant
