### ISSUE TITLE
Add the Bot

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/opendatahub-operator#539]
I made no attempt to use your template or to search for an issue -- sorry 😅 

Have you considered adding the bot to this repo -- Harshad added one to the opendatahub-community repo and it seems to allow for commands like `/transfer` -- https://github.com/openshift/release/pull/43275

Might have value to take bugs from here to our components as we figure out who owns it.

**Comment by andrewballantyne** [comment]
eg. For https://github.com/opendatahub-io/opendatahub-operator/issues/519 to move to Dashboard

**Comment by zdtsw** [comment]
does it mean anyone can run this "/transfer <target-repo>" command?
or only thoese with reviewer/approver permission in both "source" and "tareget" repo?

**Comment by andrewballantyne** [comment]
GitHub allows direct movement if you're admin on both sides of the fence. I do it all the time with the community repo. What permissions does the bot need? I have seen it have problems when people are not part of the ODH (or Red Hat?) group just assigning them to the ticket. I do not know what limitations exist -- you'd need to investigate that.

As it stands today, we cannot transfer away from this Operator repo and it seems people are logging bugs on your side purely because the v2 Operator was used. I imagine this will continue happening. Either we close the issue and relog it, I get myself admin on your repo, or we add the bot. I'm not sure we have an alternative, I'm open to other suggestions.

**Comment by zdtsw** [comment]
> GitHub allows direct movement if you're admin on both sides of the fence. I do it all the time with the community repo. What permissions does the bot need? I have seen it have problems when people are not part of the ODH (or Red Hat?) group just assigning them to the ticket. I do not know what limitations exist -- you'd need to investigate that.
> 
> As it stands today, we cannot transfer away from this Operator repo and it seems people are logging bugs on your side purely because the v2 Operator was used. I imagine this will continue happening. Either we close the issue and relog it, I get myself admin on your repo, or we add the bot. I'm not sure we have an alternative, I'm open to other suggestions.

I am not against the idea of using bot.
But i am not admin in any of the ODH/RHODS repo, not sure how exactly we can create a bot and grant permission to it.
if you have some docs/instruction that will be helpful.
I leave @VaishnaviHire for more inputs.

**Comment by andrewballantyne** [comment]
@harshad16 (tagged so he can add any knowledge on the topic) used https://github.com/openshift/release/pull/43275 to setup the bot and then was able to transfer an issue in the opendatahub-community repo... I would imagine it is the same thing.

**Comment by harshad16** [comment]
The command transfer issue from prow 
would allow **all the org members** to do the action.
based on the description here: https://prow.k8s.io/command-help#transfer_issue

earlier i had thought it only allow admin.
the admin-only behavior is from GitHub side.

If we would like only admins, to move issue
then we can directly rely on GitHub
