### ISSUE TITLE
[follow-up]: enable all linters by default with exceptions and fix the rest warning/issues

### ISSUE THREAD

**Issue by zdtsw** [opendatahub-io/opendatahub-operator#553]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
This issue is to followup https://github.com/opendatahub-io/opendatahub-operator/pull/540#discussion_r1332834176

**Describe alternatives you've considered**

**Additional context**
we might also breakdown some functions e.g e2e test due to high cyclomatic complexity

**Comment by AjayJagan** [comment]
@zdtsw @bartoszmajsak  -> we are still considering to `enable-all: true` and then disable only a few right?

**Comment by zdtsw** [comment]
> @zdtsw @bartoszmajsak -> we are still considering to `enable-all: true` and then disable only a few right?

yes, the goal is to make enable-all possible with some exceptions.

**Comment by AjayJagan** [comment]
one more qn: should we consider running the lint as a pre-commit hook?(I dont know if that is possible, I have done it for front-end applications) so that it runs before every commit
wdyt?

**Comment by zdtsw** [comment]
> one more qn: should we consider running the lint as a pre-commit hook?(I dont know if that is possible, I have done it for front-end applications) so that it runs before every commit wdyt?

i dont think it need to be every commit, as long as per PR it should be fine. and since it is already run in GH action, if the linter fails, author should fix it or PR wont get merged.
pre-commit check can be done in git hook, but since this is community project i would not think it is necessary.

**Comment by AjayJagan** [comment]
cool! got it

**Comment by AjayJagan** [comment]
Migrated to JIRA: https://issues.redhat.com/browse/RHOAIENG-496, hence closing it here.
