### ISSUE TITLE
Verify cleanup of odh-deployer resources.

### ISSUE THREAD

**Issue by VaishnaviHire** [opendatahub-io/opendatahub-operator#587]
This is a tracker issue to ensure there are no additional resources like duplicate secrets/configmaps as part of upgrade

odh-deployer repo: https://github.com/red-hat-data-services/rhods-operator

**Comment by VaishnaviHire** [comment]
This is a subtask of #461. Not adding `qe-verification` label, since it will be tested as part of upgrade.

**Comment by lugi0** [comment]
I see a problem with this, there are duplicate configmaps for DSPO-config and DSPO-parameters
![image](https://github.com/opendatahub-io/opendatahub-operator/assets/82518733/bd06af6a-a969-4206-8848-7be033044d8b)

**Comment by diegolovison** [comment]
cc @HumairAK

**Comment by lugi0** [comment]
AFAIK the controller of the component is responsible for creating / cleaning up its own resources, but let me ping @zdtsw @VaishnaviHire for a proper answer

**Comment by VaishnaviHire** [comment]
Hi @lugi0 @HumairAK Wouldn't this be an issue with v1.x upgrades as well? 



This is correct, operator would not be able to add `owner references` to the resources it doesn't create. So component controller needs to manage the generated resources.
> AFAIK the controller of the component is responsible for creating / cleaning up its own resources, but let me ping @zdtsw @VaishnaviHire for a proper answer

**Comment by VaishnaviHire** [comment]
@HumairAK Alternatively, manifests can be moved to kustomize v5 where params configmap is not generated

**Comment by zdtsw** [comment]
i was thinking about this, wont other component which uses configmap generator have the same problem?

**Comment by VaishnaviHire** [comment]
Yeah, however this is not introduced by the upgrade path and would be fixed when https://github.com/opendatahub-io/opendatahub-operator/issues/714 is completed

**Comment by HumairAK** [comment]
>AFAIK the controller of the component is responsible for creating / cleaning up its own resources
> operator would not be able to add owner references to the resources it doesn't create

These resources are created _when the dspo is deployed_, it is my understanding the ODH operator does a kustomize build behind the scene, and applies the manifests, so it's ODH that creates these manifests. 

> @HumairAK Wouldn't this be an issue with v1.x upgrades as well?

Yes

> @HumairAK Alternatively, manifests can be moved to kustomize v5 where params configmap is not generated

Not sure I follow, do you have a reference link? I haven't looked into v5 much. 

We can just make these configmap names not generated, but any changes to the configmap would require a restart of the deployment, it's not ideal, but if this is the formula the rest of the components are following, we can follow suite.

**Comment by zdtsw** [comment]
> @VaishnaviHire @zdtsw @HumairAK is this planned to be fixed inside RC2? or are we moving it to a future release?

dont think we had logic updated from operator side for getting this in RC2

**Comment by VaishnaviHire** [comment]
@lugi0 This is not included in RC2. It will be fixed as part of https://github.com/opendatahub-io/opendatahub-operator/issues/714 . As Humair confirmed, this issue is not introduced in v1-->v2 upgrade

@HumairAK Kustomize v5 does not support param.env https://github.com/kubeflow/manifests/issues/538

**Comment by hbelmiro** [comment]
@VaishnaviHire I'm not sure I'm following.
DSPO is already using the new syntax: https://github.com/opendatahub-io/data-science-pipelines-operator/blob/5dbf01264bd479591d2dfca89007b005f787b4d1/config/base/kustomization.yaml#L15C7-L15C7

cc @HumairAK

**Comment by VaishnaviHire** [comment]
Moving discussion to jira as part of epic for #714
