### ISSUE TITLE
Allow access to DataScienceCluster component statuses for basic OpenShift Console users

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/opendatahub-operator#588]
**Is your feature request related to a problem? Please describe.**
The Dashboard would like to start relying heavily on the status of the Operator's DSC CR, so we can know what components are installed so we can override our feature flags. Ideally this will grow to support issues with installation issues of components. (eg. https://github.com/opendatahub-io/odh-dashboard/issues/1886 -- which seems to have some details already)

**Describe the solution you'd like**
An out-of-the-box role to grant all `system:authenticated` users access to the `.status` of the DSC.

akin to `kubectl create role foo --verb=get,list,watch --resource=pods/status`

**Describe alternatives you've considered**

- The Dashboard Service Account pulls the information and filters it before handing it off to the Dashboard client.
- A new resource, like a configmap/CR or something could hold onto the information about install status

**Additional context**
A final note on how we approach this: we will just have to be careful about **any** information we put on the status and make sure we aren’t leaking any potentially sensitive information about the underlying cluster. Such as any human readable messages

**Comment by zdtsw** [comment]
i think the more accurate one to use is `InstalledComponents` from `.status` of DSC to use.
in case, the component is enabled but keep reconciling , it gets to set  to false.

**Comment by andrewballantyne** [comment]
It should be noted -- this seems not possible to do at a subresource **only** level. My test & results can be found [on slack](https://redhat-internal.slack.com/archives/C0562LQBWMP/p1697659998919139?thread_ts=1697657485.979729&cid=C0562LQBWMP).

**Comment by AjayJagan** [comment]
Migrated to JIRA: https://issues.redhat.com/browse/RHOAIENG-493, hence closing it here.
