### ISSUE TITLE
V0.8.0 jupyterhub deploy failed 

### ISSUE THREAD

**Issue by Algimantus** [opendatahub-io/opendatahub-operator#59]
V0.8.0 jupyterhub-1-deploy failed with following error:

    oc logs jupyterhub-1-deploy-2-s5tsq

    error: update acceptor rejected jupyterhub-1-deploy-2: pods for rc 'default/jupyterhub-1-deploy-2' took longer than 600 seconds to become available

---
oc logs jupyterhub-1-deploy-6-72th7
Error from server (BadRequest): container "jupyterhub-1-deploy" in pod "jupyterhub-1-deploy-6-72th7" is waiting to start: trying and failing to pull image

Same situation with superset...

Any suggestions welcome

**Comment by edvinas31** [comment]
oc get events output may be found attached 
![oclogs2](https://user-images.githubusercontent.com/49708029/93074196-b1f99680-f68c-11ea-9b74-cc8c981d6616.PNG)
![oclogs1](https://user-images.githubusercontent.com/49708029/93074205-b45bf080-f68c-11ea-87fc-a9da9633eb1d.PNG)

**Comment by vpavlin** [comment]
Hi,

Can you share the KFDef?

Can you also share the output of 

```oc describe is jupyterhub-img```

**Comment by edvinas31** [comment]
Hi, of course

![image](https://user-images.githubusercontent.com/49708029/93093441-5d184900-f6a9-11ea-928c-dedb6dbf5b39.png)

![image](https://user-images.githubusercontent.com/49708029/93094683-e8460e80-f6aa-11ea-9b59-2eb9c1fa1af9.png)

![image](https://user-images.githubusercontent.com/49708029/93094737-fa27b180-f6aa-11ea-97b2-c48c0b03dfe8.png)

![image](https://user-images.githubusercontent.com/49708029/93094776-04e24680-f6ab-11ea-96c2-5c246b36eb0a.png)

**Comment by vpavlin** [comment]
This issue was due to ODH being deployed to `default` namespace. Deploying to `default` is generally discouraged since it is a "special" namespace in OpenShift
