### ISSUE TITLE
Update V2 Operator to account for Distributed Workloads deployment update

### ISSUE THREAD

**Issue by anishasthana** [opendatahub-io/opendatahub-operator#600]
https://github.com/opendatahub-io/architecture-decision-records/pull/21 is proposing a new deployment strategy for the Distributed Workloads stack, so the operator needs to be updated to account for it.

In short:

1) CodeFlare controller manifests and CRDs will be deployed by the ODH operator. The manifests will exist in https://github.com/opendatahub-io/codeflare-operator/
2) The KubeRay manifests will be moved over into the https://github.com/opendatahub-io/kuberay fork.

cc @astefanutti @dimakis @sutaakar

**Comment by zdtsw** [comment]
are we gonna sunset https://github.com/opendatahub-io/distributed-workloads in favor of https://github.com/opendatahub-io/codeflare-operator/config and https://github.com/opendatahub-io/kuberay/config?
if yes, do yo have a plan for this switch? odh-1.11/rhods1.35? @anishasthana

**Comment by anishasthana** [comment]
Yes, ODH 1.11 / RHODS 1.35 is the targeted timeline

**Comment by astefanutti** [comment]
Requires #619.

**Comment by zdtsw** [comment]
close this as it has been included in odh 2.4 and downstream
