### ISSUE TITLE
Errors during upgrade operation in rhods operator

### ISSUE THREAD

**Issue by jstourac** [opendatahub-io/opendatahub-operator#603]
**Describe the bug**

When upgrading from RHODS 1.32 to RHODS 1.33 there can be seen following errors in the log of the rhods operator pod: 

`rhods-operator` container:
```
rhods-operator-796d77d975-2s2dr-rhods-operator.log:time="2023-10-05T09:14:47Z" level=error msg="Could not create metrics Service. Error: failed to create or get service for metrics: services \"rhods-operator-metrics\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>."
```

`rhods-deployer` container:
```
rhods-operator-796d77d975-2s2dr-rhods-deployer.log:Error from server (AlreadyExists): error when creating "monitoring/prometheus/prometheus-secrets.yaml": serviceaccounts "prometheus" already exists
rhods-operator-796d77d975-2s2dr-rhods-deployer.log:Error from server (AlreadyExists): error when creating "monitoring/prometheus/prometheus-secrets.yaml": secrets "prometheus-proxy" already exists
rhods-operator-796d77d975-2s2dr-rhods-deployer.log:Error from server (AlreadyExists): error when creating "monitoring/prometheus/prometheus-secrets.yaml": secrets "alertmanager-proxy" already exists
rhods-operator-796d77d975-2s2dr-rhods-deployer.log:Error from server (AlreadyExists): error when creating "monitoring/prometheus/prometheus-secrets.yaml": secrets "prometheus-secret" already exists
```

Not sure about the error from the `rhods-operator` container but those errors from `rhods-deployer` seem to be caused by the fact that some resources already exist on the cluster. Obviously because of the presence of the previous version.

Tested with RHODS 1.32 to 1.33, managed; version 1 operator.

**To Reproduce**

1. On OpenShift cluster with RHODS 1.32 operator installed, go to `Operators -> Installed Operators -> Red Hat OpenShift Data Science`
2. Click on operator update button
3. Now move to `Workloads -> Pods`, select the `redhat-ods-operator` namespace adn search for `rhods-operator-*` pod instance.
4. Open it and see logs for `rhods-operator` and `rhods-deployer` containers.

**Expected behavior**

Ideally no errors to be part of the log at all. These messages should be able to avoid - e.g. we know that we're doing the upgrade and the code can omit them in such case. Otherwise these may be misleading for the user.

**Additional context**

Haven't tried this with operator v2 but if there is anything similar, it would deserve to check and fix there too.

**Comment by zdtsw** [comment]
@jstourac thanks for reporting this!

Apart from error logs from `rhods-deplo`y, is there any other functional error?

**Comment by jstourac** [comment]
Hi @zdtsw,

no, I didn't see any functional error of the rhods operator pod after the upgrade finished. This isn't a blocker for users. But may be misleading when doing some logs checking, so it shouldn't be present.

I understand that v1 is on the way to die soon. We should probably check and eventually avoid similar issue in v2 if possible.

**Comment by zdtsw** [comment]
@jstourac if no objection, we will have this issue close because we will only release new version of ODH for v2 operator.

**Comment by jstourac** [comment]
@zdtsw yeah, sure. Understand. I'll try to check on the v2 later more.
