### ISSUE TITLE
Enable Service Mesh Auth(z) settings for KServe

### ISSUE THREAD

**Issue by bartoszmajsak** [opendatahub-io/opendatahub-operator#614]
Configure KServe component to leverage Service Mesh unified authentication and authorization solution. This integration will streamline the security protocols, making it easier to manage, more secure, and scalable. 

Service Mesh should be configured to work seamlessly with KServe, ensuring that all the services deployed are automatically covered under the umbrella of its Auth(z) features. 

Depends on #605

**Comment by bartoszmajsak** [comment]
WIP https://github.com/maistra/opendatahub-operator/pull/13

**Comment by bartoszmajsak** [comment]
Depends on #605

**Comment by AjayJagan** [comment]
Migrated to JIRA: https://issues.redhat.com/browse/RHOAIENG-514, hence closing this here.
