### ISSUE TITLE
Scaling down OpenDataHub Replicas on OpenShift

### ISSUE THREAD

**Issue by artrza** [opendatahub-io/opendatahub-operator#629]
Hello all,

im wokring with OpenDataHub in Openshift and i wanted to scale down some resource to 1 replica. But i didnt see anywhere in the CR to do it. Is there someway to do it?

Thank you

**Comment by zdtsw** [comment]
hi @artrza
can you brief what kind of resource you want to scale down? 
is it e.g the pod of odh-dashboard?

**Comment by artrza** [comment]
For Example:

Data-science-pipeline-operator-controller-manager -> 3 Pods (wanted to 1 )
modelmesh-controller -> 3 Pods
odh-model-controller -> 3 Pods
odh-dashboard -> 2 Pods

**Comment by artrza** [comment]
Thank you for ur fast reply. Can u please show me an Example CR how it could should look like#?

Thank you

**Comment by zdtsw** [comment]
You can refer to https://github.com/opendatahub-io/opendatahub-operator/wiki/3.-Using-Operator-in-Dev-Mode

Please be aware, devFlags is only for development mode, if you apply it to your production and cause any destructible consequence we won't be able to help

**Comment by zdtsw** [comment]
if no future action on this issue, i would like to have it closed for now.

you are welcome to contact us on our slack "support" channel https://odh-io.slack.com/archives/C0330L52N22
