### ISSUE TITLE
Codeflare - RHODS Reconciliation error after roles update

### ISSUE THREAD

**Issue by asanzgom** [opendatahub-io/opendatahub-operator#635]
This issue is a continuation of https://github.com/opendatahub-io/opendatahub-operator/issues/550

I reproduced the following error with RHODS v1.34 Operator (592170) + Codeflare v1.33:

`Component reconciliation failed: [mcads.codeflare.codeflare.dev](http://mcads.codeflare.codeflare.dev/) “mcad” is forbidden: User “system:serviceaccount:redhat-ods-operator:redhat-ods-operator-controller-manager” cannot patch resource “mcads” in API group “[codeflare.codeflare.dev](http://codeflare.codeflare.dev/)” in the namespace “redhat-ods-applications”`

with Codeflare v1.34 (592158) reproduced the same reconcile error: 

![image](https://github.com/opendatahub-io/opendatahub-operator/assets/100594859/c0536510-7fd7-473b-aadf-59266160a49b)

**Comment by zdtsw** [comment]
this need to be fixed in the midstream

**Comment by zdtsw** [comment]
fix in https://gitlab.cee.redhat.com/data-hub/rhods-cpaas-midstream/-/merge_requests/1266

**Comment by zdtsw** [comment]
close it as has been verified by qe
