### ISSUE TITLE
Add missing resources to manage in DSC controller

### ISSUE THREAD

**Issue by VaishnaviHire** [opendatahub-io/opendatahub-operator#637]
**Is your feature request related to a problem? Please describe.**
Currently operator is managing resources it creates, however it doesn't reconcile on update/deletion of resources if they are not listed as `Owns` under [SetupWithManager](https://github.com/opendatahub-io/opendatahub-operator/blob/incubation/controllers/datasciencecluster/datasciencecluster_controller.go#L295) function.

**Describe the solution you'd like**
Extend the list of resources to include resource types previously defined in v1 -
[List of resource types
](https://github.com/opendatahub-io/opendatahub-operator/blob/master/controllers/kfdef.apps.kubeflow.org/kfdef_controller.go#L269-L289)

**Additional context**
One of the tests that we can perform to verify the change is to ensure the resources that are not previously in the list get recreated on deletion - 
1. Deploy operator image with changes
2. Set `workbenches` component to Managed in DSC instance
3. Delete any `Imagestream` under  `opendatahub` namespace.
4. Verify if the `Imagestream` gets recreated.

**Comment by ykaliuta** [comment]
is label rhods-1.35 correct here?

**Comment by zdtsw** [comment]
> is label rhods-1.35 correct here?

should be 2.4.
do you want to get it in 1.35/2.4 ? or 2.5 ?

**Comment by ykaliuta** [comment]
> > is label rhods-1.35 correct here?
> 
> do you want to get it in 1.35/2.4 ? or 2.5 ?

Well, as soon as it gets integration. Will be safe to put 2.5 or 2.4 still sounds feasible?

**Comment by zdtsw** [comment]
ref https://github.com/opendatahub-io/opendatahub-operator/issues/613

**Comment by zdtsw** [comment]
PR613 did ont get into rhods-2.4 but does in odh-2.4
since we will not have test on odh-2.4, move label to odh-2.5 and rhods-2.5 instead.
