### ISSUE TITLE
Deprecation of the ODH 1.x operator

### ISSUE THREAD

**Issue by LaVLaS** [opendatahub-io/opendatahub-operator#648]
With the release of ODH 1.11, the plan is to [EOL](https://en.wikipedia.org/wiki/End-of-life_product) the kfdef operator and migrate to the [DataScienceCluster](https://github.com/opendatahub-io/opendatahub-operator/blob/incubation/docs/DESIGN.md) as the new API for managing ODH deployments on OpenShift.

- [ ] opendatahub.io: Set the odh-operator v2.x instructions as the default [Installation](https://opendatahub.io/docs/quick-installation) instructions
- [ ] opendatahub.io: Move the odh-operator v1.x to a "legacy" doc.  
- [ ] opendatahub.io: Blog stating the deployment of ODH using `kfdef` is no longer supported with instructions on how to migrate (see #631) from v1.x --> v2.x
- [ ] openatahub-operator: Update the README on [master](https://github.com/opendatahub-io/opendatahub-operator/tree/master) to reflect that it will no longer be updated

**Comment by zdtsw** [comment]
should we also add
- archive ODH odh-manifests
- archive downstream odh-deployer
- update downstream odh-manifests README that only odh-dashboard will be updated to release branch etc.

**Comment by AjayJagan** [comment]
This seems like a Epic to me wdyt @VaishnaviHire

**Comment by AjayJagan** [comment]
Here is the corresponding JIRA : https://issues.redhat.com/browse/RHOAIENG-810. Hence closing it here.
