### ISSUE TITLE
Servicemesh Kserve integration

### ISSUE THREAD

**Issue by VaishnaviHire** [opendatahub-io/opendatahub-operator#666]
Kserve component requires servicemesh resources like Servicemesh controlplane, servicemeshmemberroles etc.

This is a tracker issue for changes required for operator changes for Kserve + Servicemesh integration

**Comment by jkoehler-redhat** [comment]
@VaishnaviHire can you please add the issues for service mesh and kserve?

**Comment by bdattoma** [comment]
@VaishnaviHire what about Serverless operator? it is needed as well. Does it have a dedicated GH issue?

**Comment by bdattoma** [comment]
duplicate issue: https://github.com/opendatahub-io/kserve/issues/105
