### ISSUE TITLE
Add support for ACID table format in ODH

### ISSUE THREAD

**Issue by sstsalazar** [opendatahub-io/opendatahub-operator#67]
Greetings everyone,

  As support for Presto is being considered in ODH as seen in the issue [#51](https://github.com/opendatahub-io/opendatahub-operator/issues/51) I'd like to suggest adding support for an ACID table format in ODH in order to improve data quality assurance. The most common open source solutions seems to be:

- [Apache Iceberg](https://iceberg.apache.org/)
- [Apache Hudi](https://hudi.apache.org/)
- [Databricks' Delta Lake](https://delta.io/)

Although theses solutions are not 100% feature equal, they mostly cover the most popular features such as:
- ACID support
- Integration with Spark and Presto
- MVCC
- Time travel
- Schema Evolution
- Streaming support
- Compaction and Cleanup
- S3a support

Therefore including one of these solutions in ODH stack would strengthen the whole project, IMHO.

**Comment by vpavlin** [comment]
Hi @sstsalazar! Thanks for the suggestion.

Can you attend our community meeting (https://gitlab.com/opendatahub/opendatahub-community/-/wikis/Open-Data-Hub-Community-Meeting-Agenda) and talk about this proposal?

Would you also be able to contribute one of those to https://github.com/opendatahub-io/odh-manifests/?
