### ISSUE TITLE
Test automation for Servicemesh Kserve integration

### ISSUE THREAD

**Issue by asanzgom** [opendatahub-io/opendatahub-operator#680]
This issue is to create automated tests both on ods-ci and odh repo sides for the following feature:
https://github.com/opendatahub-io/opendatahub-operator/issues/666

**Comment by bartoszmajsak** [comment]
@asanzgom Thank you for initiating this important discussion on automated tests. This sounds more like an epic to me so let's break it down into more manageable tasks. We should identify the different types of tests we need and clarify who will be owning each segment. I'm excited to see everyone's input on this so we can ensure a well-rounded test strategy.

So far, I've considered the following types of tests:

- end-to-end tests covering flows through Dashboard
- integration tests involving operator+kserve+service mesh
- unit and fast integration tests (using k8s testenv) run only against controllers being part of the operator and resources they own (they are coming as part of #691)

Anything else we would like to build as safety nets?

**Comment by AjayJagan** [comment]
Migrated to JIRA: https://issues.redhat.com/browse/RHOAIENG-485 and so closing it here.
