### ISSUE TITLE
Validate fields for DSCI and DSC

### ISSUE THREAD

**Issue by zdtsw** [opendatahub-io/opendatahub-operator#693]
**Is your feature request related to a problem? Please describe.**

We have certain code logic to check e.g if the number of instance is over 1, the name of the instance, etc.
It would be good to implement  webhook for these validation, so we do not have such logic everywhere and hard to maintain them.
the current validation I can think of is:
- we only support single instance
- we only support "default" as DSCI instance name.
this can be extended later depends on new requirements

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by AjayJagan** [comment]
Migrated to JIRA: https://issues.redhat.com/browse/RHOAIENG-484, hence closing the issue.
