### ISSUE TITLE
[Tracker] Prepare to upgrade to kustomize v5

### ISSUE THREAD

**Issue by zdtsw** [opendatahub-io/opendatahub-operator#714]
**Is your feature request related to a problem? Please describe.**
This is more like a tracker issue to ensure all components including operator to be able to run kustomize v5.x 

- [ ] operator
- [ ] dashboard
- [ ] kserve
- [ ] modelmesh
- [ ] dsp
- [ ] trustyai
- [ ] codeflare
- [ ] ray

**Comment by AjayJagan** [comment]
can I create an epic for the kustomize v5 upgrade? wdyt @VaishnaviHire

**Comment by AjayJagan** [comment]
Here is the corresponding Epic JIRA for the same: https://issues.redhat.com/browse/RHOAIENG-809. We can track it here and hence closing it here.
