### ISSUE TITLE
opendatahub namespace and default DSCInitialization always created

### ISSUE THREAD

**Issue by shalberd** [opendatahub-io/opendatahub-operator#720]
**Describe the bug**
After install of v2.4 operator, a DSCInitialization named default is created with spec.applicationsNamespace: opendatahub

Also, the operator creates a namespace named opendatahub.

**To Reproduce**

**Expected behavior**

- opendatahub namespace is not automatically created by the operator
- no DSCInitialization named default is created
- instead, the operator listens to any DSCInitialization created and only then proceeds to create the namespace listed under spec.applicationsNamespace in that DSCInitialization ... **but only if the namespace does not yet exist**

**Screenshots**

**Additional context**
corporate cluster admins do not like having namespaces created automatically.
Also, a namespace being created and to be used by the operator for software deployment might already exist. 

Let users handle ODH main namespace creation if possible, not the operator.

Or at the very least, check for setting in spec.applicationsNamespace and only create the namespace if it does not yet exist.

**Comment by shalberd** [comment]
@HumairAK writes something similar in a [DSPO issue](opendatahub-io/data-science-pipelines-operator/issues/453):

**Comment by AjayJagan** [comment]
JIRA issue: https://issues.redhat.com/browse/RHOAIENG-410

**Comment by AjayJagan** [comment]
SInce this is migrated to JIRA, closing it here.
