### ISSUE TITLE
enhancement: simplify v2 workbenches logic, add component notebookController or similar

### ISSUE THREAD

**Issue by shalberd** [opendatahub-io/opendatahub-operator#726]
**Is your feature request related to a problem? Please describe.**
Currently, using custom developer manifests with devFlags in v2 DataScienceCluster CR is full of stumbling blocks due to the nature of workbenches component code.

**Describe the solution you'd like**

The logic of using DevFlags [in workbench](https://github.com/opendatahub-io/opendatahub-operator/blob/incubation/components/workbenches/workbenches.go#L38) is more complex than other components but this is also due to the fact that workbench need to deal with : notebook images and 2 different NBC.

Kubeflow notebook controller and odh notebook controller really should be a separate component from workbenches. At the very least, having a component notebookControllers or something like that.

Workbenches then just being the imagestream definitions / images that come standard or in the overlay with ODH. That way, then, the logic in workbench go code would be much more streamlined. I think Vaishnavi and you already talked about that possibility.

Also, please think about not having a hard-coded word match for "notebooks" in the url to the imagestreams / workbenches.

**Describe alternatives you've considered**

**Additional context**
see my problems installing developer manifests for workbenches / custom, i.e. PR-related manifests for kubeflow- and odh notebook controller in #719 that @zdtsw helped me navigate through.

**Comment by AjayJagan** [comment]
Migrated to JIRA: https://issues.redhat.com/browse/RHOAIENG-480, hence closing the issue here.
