### ISSUE TITLE
Refining RBAC Annotation Placement and Permissions

### ISSUE THREAD

**Issue by bartoszmajsak** [opendatahub-io/opendatahub-operator#732]
We initially transferred RBAC `kubebuilder` annotations from controllers to a centralized `kubebuilder_rbac.go` file to enhance code readability. However, this approach has scalability issues, as it ended up as one huge bag of all the roles for every component. To resolve this, we should relocate these annotations back to the specific controllers and components where they are required. While doing so, we can maintain a conventional structure by continuing to use `kubebuilder_rbac.go` files within these folders. Additionally we should check if we do not define `// +kubebuilder:rbac` anywhere else in the code.

Additionally, this task involves a thorough review and update of our RBAC rules. Our goal is to ensure that all necessary permissions are accurately defined, minimizing the use of broad permissions (e.g., using '*' permissions) to enhance security and efficiency.

**Comment by bartoszmajsak** [comment]
As part of this work we might want to consider removing RBAC rules for DeploymentConfig, as it is deprecated. I'm seeing this in the logs:

```
apps.openshift.io/v1 DeploymentConfig is deprecated in v4.14+, unavailable in v4.10000+
```

Not quite sure we touch anything `DeploymentConfig`

**Comment by zdtsw** [comment]
> As part of this work we might want to consider removing RBAC rules for DeploymentConfig, as it is deprecated. I'm seeing this in the logs:
> 
> ```
> apps.openshift.io/v1 DeploymentConfig is deprecated in v4.14+, unavailable in v4.10000+
> ```
> 
> Not quite sure we touch anything `DeploymentConfig`

not directly in operator, but notebook or dashboard might have some part
