### ISSUE TITLE
RHODS Managed 2.4 fails to completely uninstall

### ISSUE THREAD

**Issue by lugi0** [opendatahub-io/opendatahub-operator#747]
**Describe the bug**
The RHODS addon in Managed clusters on version 2.4 fails to completely uninstall. Once the uninstallation is triggered from OCM/OSD the rhods-notebooks namespace and all pods in all rhods namespaces are removed (including the operator pod). However the redhat-ods-applications, redhat-ods-monitoring and redhat-ods-operator namespaces are left in the cluster, the addon-managed-odh-catalog pod is left running in the redhat-ods-operator namespace and OCM/OSD keep reporting the addon as "Uninstalling" for 2 hours, and after that switching to "Add-on failed" and prompting users to contact Red Hat support.

**To Reproduce**
1. Install RHODS Addon in an OSD cluster
2. Wait for it to go to "Installed" state
3. Trigger uninstall from OSD/OCM

**Expected behavior**
RHODS is fully cleaned up and OCM/OSD report the addon as uninstalled

**Screenshots**

![image](https://github.com/opendatahub-io/opendatahub-operator/assets/82518733/fde1b7cf-5a80-4860-b22a-743d0784f0b2)
![image](https://github.com/opendatahub-io/opendatahub-operator/assets/82518733/ce5b27a3-89a5-4644-88b8-83c2d1210ad0)
![image](https://github.com/opendatahub-io/opendatahub-operator/assets/82518733/73dec1c4-729c-46dc-b8f9-28b748a2470b)
![image](https://github.com/opendatahub-io/opendatahub-operator/assets/82518733/66d8c9ae-0568-41bd-b670-a4018305590d)

**Additional context**

**Comment by lugi0** [comment]
No, all the pods are actually removed, but the namespaces are still present

**Comment by bartoszmajsak** [comment]
@lugi0 is the operand (controller) pod producing any logs or keeps restarting? I think I am encountering similar issue but wanted to make sure we are talking about the same problem.

**Comment by lugi0** [comment]
@bartoszmajsak from what I've seen all pods are deleted, so no logs and no restarts

**Comment by bartoszmajsak** [comment]
> @bartoszmajsak from what I've seen all pods are deleted, so no logs and no restarts

@lugi0 does it include controller pod as well?

**Comment by zdtsw** [comment]
yep from what i see 3 redhat-ods-* NS are in cluster ,but no pod in any of these three.

**Comment by lugi0** [comment]
This was a configuration issue in the testing environment and we have found the root cause. Closing as it's not applicable anymore. Thanks all!
