### ISSUE TITLE
Make the Data Science Cluster object failing in case of components enablement issues

### ISSUE THREAD

**Issue by bdattoma** [opendatahub-io/opendatahub-operator#750]
**Is your feature request related to a problem? Please describe.**
At the moment, the DSC reports the error inside when you open it, but the overall status remains "Ready" with a green tick
This could help to mitigate the issue of silent errors when KServe (or any other components) fails to be enabled, e.g., because missing the required operators.

**Describe the solution you'd like**
Overall status considers the status of the components which are supposed to be enabled

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by zdtsw** [comment]
same as https://github.com/opendatahub-io/opendatahub-operator/issues/654 ? @bdattoma

**Comment by bdattoma** [comment]
> same as #654 ? @bdattoma

hm it depends: if after #654 gets implemented, the DSC overall status is not "Ready" when components fail to install, then yes.
