### ISSUE TITLE
Add common selector labels for pods

### ISSUE THREAD

**Issue by ajaypratap003** [opendatahub-io/opendatahub-operator#754]
**Is your feature request related to a problem? Please describe.**
Original issue was overlap default selector labels with other components pods. Default selector labels have updated in this [PR](https://github.com/opendatahub-io/opendatahub-operator/pull/751)
and one more suggestion came for adding common labels  i.e. 
-   app.kubernetes.io/name
-   app.kubernetes.io/component
-  app.kubernetes.io/part-of
-  etc

 https://github.com/opendatahub-io/opendatahub-operator/pull/751#discussion_r1397472007

**Describe the solution you'd like**

- Add common labels for pods and service https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by AjayJagan** [comment]
Hi @ajaypratap003 , this can be tracked here: https://issues.redhat.com/browse/RHOAIENG-453
So if you feel this is okay, you can close it :)
