### ISSUE TITLE
Multiple DSCInitialization resources cause Operator CrashLoop

### ISSUE THREAD

**Issue by aslakknutsen** [opendatahub-io/opendatahub-operator#755]
**Describe the bug**

If multiple DSCInitialization resources exists on the cluster the Operator calls a nil pointer and end in a CrashLoop

**To Reproduce**
1. create a DSCInitialization named "default"
1. create a DSCInitialization named "default-dsci" (probably not required to create manually as one will be created for you)
4. See Operator Console log

**Expected behavior**
A clear and concise description of the problem

**Additional context**

https://github.com/opendatahub-io/opendatahub-operator/blob/3ca6f45ea06df045a4fb7af0063268972b997dda/controllers/dscinitialization/dscinitialization_controller.go#L86-L94

86: creates a Empty instance
92: check the list of all dsci, woops we have more then 1
94: update the status of the empty instance

**Comment by ykaliuta** [comment]
Should we finally integrate https://github.com/opendatahub-io/opendatahub-operator/pull/711 ?

**Comment by zdtsw** [comment]
> Should we finally integrate #711 ?

yes, 
what i am thinking is like this: to have this fix in odh-2.5 release.
because a workaround has been done in downstream 2.5

then we can have you webhook in odh-2.6, sounds good? @ykaliuta

**Comment by ykaliuta** [comment]
> then we can have you webhook in odh-2.6, sounds good? @ykaliuta

Wonderful!

**Comment by AjayJagan** [comment]
JIRA issue for the same : https://issues.redhat.com/browse/RHOAIENG-412

**Comment by AjayJagan** [comment]
closing this and tracking in the above JIRA link.
