### ISSUE TITLE
field "time" is not updated for some CR conditions in DataScienceCluster

### ISSUE THREAD

**Issue by jgarciao** [opendatahub-io/opendatahub-operator#759]
**Describe the bug**

The field _Updated_ in  the CR conditions ReconcileComplete, Available, Progressing, Degraded and Upgradeable is not being updated, while other columns for the same rows, like Reason and Message are updated when there are changes in the custom resource.

![image](https://github.com/opendatahub-io/opendatahub-operator/assets/66894/8992e087-f913-493c-981b-d768ddfab1f7)

**Comment by AjayJagan** [comment]
JIRA link: https://issues.redhat.com/browse/RHOAIENG-413

**Comment by AjayJagan** [comment]
This issue will be tracked in the above JIRA link, hence closing it.
