### ISSUE TITLE
replace to use ExponentialBackoffWithContex call in the code

### ISSUE THREAD

**Issue by zdtsw** [opendatahub-io/opendatahub-operator#763]
**Is your feature request related to a problem? Please describe.**

we have mixed calls in the code to use  `wait.PollUntilContextTimeout()` `wait.ExponentialBackoffWithContex()` for similar reason.
the later one is the preferred way o align with k8s implementation.

**Describe the solution you'd like**

update the code to use `wait.ExponentialBackoffWithContex()` only
and do thoroughly tests with  turning of the values in param

**Comment by AjayJagan** [comment]
JIRA issue: https://issues.redhat.com/browse/RHOAIENG-452
