### ISSUE TITLE
Add Contributing Guidelines for Upstream Downstream Sync

### ISSUE THREAD

**Issue by VaishnaviHire** [opendatahub-io/opendatahub-operator#764]
**Is your feature request related to a problem? Please describe.**
Currently, there is no documentation/reference on how to sync upstream changes in the downstream.

**Describe the solution you'd like**
Document steps required to get changes from upstream repo to downstream.

**Comment by zdtsw** [comment]
should we use 2.6 label?

**Comment by VaishnaviHire** [comment]
Sprint would still be 2.5 .. but for tracking code changes, probably need rhods-2.6 label
