### ISSUE TITLE
ODH Operator stuck at "UpgradePending"

### ISSUE THREAD

**Issue by Tutj** [opendatahub-io/opendatahub-operator#80]
**Describe the bug**
When trying to deploy ODH v0.9.0 on RHOCP 4.5, after subscribe to beta, it is hanging at UpgradePending and all the components of InstallPlan are Unknown
**To Reproduce**
1. Go to OperatorHub
2. Subscribe to v0.9.0
3. It is stuck at UpgradePending

**Expected behavior**
ODH operator should be up and running
**Screenshots**

**Additional context**
I am not sure it is because of Community market since when i tried to check logs of community-market pod, i did not see it downloaded v0.9.0

**Comment by nakfour** [comment]
@Tutj is this a fresh OCP 4.5 cluster? or did you have ODH 0.8 installed already?

**Comment by esperoz** [comment]
The same case in my fresh OCP 4.5.19 cluster. It fails on ContainerCreating phase with following **message in events**:

Failed to create pod sandbox: rpc error: code = Unknown desc = container create failed: time="2020-11-30T10:21:09+03:00" level=warning msg="exit status 2" time="2020-11-30T10:21:09+03:00" level=error msg="error running hook: exit status 255, stdout: , stderr: " time="2020-11-30T10:21:09+03:00" level=error msg="container_linux.go:348: starting container process caused \"process_linux.go:438: container init caused \\\"process_linux.go:421: running prestart hook 0 caused \\\\\\\"error running hook: exit status 255, stdout: , stderr: \\\\\\\"\\\"\"" container_linux.go:348: starting container process caused "process_linux.go:438: container init caused \"process_linux.go:421: running prestart hook 0 caused \\\"error running hook: exit status 255, stdout: , stderr: \\\"\""

**Comment by nakfour** [comment]
@Tutj we did have an issue with ODH 0.9 in community operators that we fixed, can you try this again.

**Comment by Tutj** [comment]
Hi Juana,

Still ODH has error as below and i think community also reports this bug
related to cache-server.

[image: Screenshot 2020-12-04 at 1.08.18 AM.png]

Otherwise, when choosing InstallPlanApproval is Automatic, i  still need to
go to Openshift-Operator and manually approve.

Br/Tuan

**Comment by LaVLaS** [comment]
The screenshot was not attached.

> Otherwise, when choosing InstallPlanApproval is Automatic, i  still need to
go to Openshift-Operator and manually approve.
Do you have any other operators in the namespace that were NOT deployed by ODH AND have their `InstallPlanApproval` set to `Manual`? There was some discussion that when multiple operators are managed by Operator Lifecycle Manager (OLM) and deployed into the same namespace if there is just one operator with `installPlanApproval` set to `Manual` then all of the operator in that namespace will be set to `Manual`.

The issues you are experiencing appear to point to an issue with OLM in your cluster. With operator stuck in `UpgradePending`, I think you have an operator `Subscription` or `ClusterServiceVersion` that is not installing correctly and blocking OLM from installing the other operators.

**Comment by Tutj** [comment]
Sorry guys, i attached here the image:
<img width="999" alt="Screenshot 2020-12-04 at 1 08 18 AM" src="https://user-images.githubusercontent.com/6781644/101120689-3d018180-3629-11eb-84b3-55942ce74a3e.png">

I re-deployed it on a clean OCP 4.5 and InstallPlanApproval is still Manual

**Comment by nakfour** [comment]
@Tutj the KF cache pods crashing are a known KF community issue and not related to operator upgrades.
