### ISSUE TITLE
After moving to ODH v2, the "Duplicate Run" feature stoped working as expected.

### ISSUE THREAD

**Issue by roytman** [opendatahub-io/opendatahub-operator#832]
**Describe the bug**
With ODH v1 we widely used the "Duplicate Run" feature. It allowed creating new Runs according previously configured Runs.
After upgrading to ODH v2, the Duplicate Run creates a new Run with the default input parameters, instead of the parameters from the duplicating RUN.

**To Reproduce**
1. Create a Run
2. Change one or more of its default input parameters. 
3. Execute the Run
4. Duplicate the Run, check that the changed input parameters returned to their default values.

**Expected behavior**
We expect that the input parameters would have values of the duplicated Run.

**Screenshots**
the original Run 
<img width="658" alt="image" src="https://github.com/opendatahub-io/opendatahub-operator/assets/1816654/0341df76-56be-4a36-954b-f5bfa3a2b8cf">

the duplicated Run 
<img width="658" alt="image" src="https://github.com/opendatahub-io/opendatahub-operator/assets/1816654/773174ad-db64-45d3-a6e1-aac6815c65a8">
Please see the iterations number

**Comment by zdtsw** [comment]
Hi, thanks for report issue!

Would you mind moving it into https://issues.redhat.com/browse/ 
(Project: Red Hat OpenShift Data Science;  Issue Type: Bug, Component/s: Platform) ?

**Comment by roytman** [comment]
Hi @zdtsw , I cannot access https://issues.redhat.com/browse/

**Comment by zdtsw** [comment]
> Hi @zdtsw , I cannot access https://issues.redhat.com/browse/

sorry for late reply, https://access.redhat.com/articles/5832311 might help to get you a new account.
I can help you migrate this issue to jira board, but still you will need account to view /comment on it.

**Comment by zdtsw** [comment]
https://issues.redhat.com/browse/RHOAIENG-2503 , thanks for @HumairAK

**Comment by zdtsw** [comment]
close this issue, follow up in https://issues.redhat.com/browse/RHOAIENG-2503
