### ISSUE TITLE
Allow custom operator permissions on cluster scope

### ISSUE THREAD

**Issue by tumido** [opendatahub-io/opendatahub-operator#85]
**Is your feature request related to a problem? Please describe.**
ODH operator has basically a `cluster-admin`  permissions once deployed. And by extension any workload deployed via the operator can leverage those permissions. By default all users with `admin` and `edit` access  on any namespace/project can deploy a `kfdef` resource which effects the whole cluster - for example by deploying other operators with all namespace access, but the application can be anything really, changing cluster roles, adding catalog sources or additional sso providers etc.

**Describe the solution you'd like**
Allow cluster admins to specify the cluster role for the operator or a service account that it would pick up if available and run within the service account RBAC. That would prevent the operator doing changes the cluster admin doesn't want the project admins to be able to do. 

**Describe alternatives you've considered**
We don't have a good solution other than defining our own Cluster service version for the operator which would define the rbac on our own. This basically equals to "forking" the operator deploy manifests.

**Additional context**
Related to #23 https://github.com/operate-first/apps/issues/167

**Comment by tumido** [comment]
cc @HumairAK @4n4nd

**Comment by HumairAK** [comment]
IMO this is a pretty big problem:

> ODH has cluster admin, ODH deploys kfdefs
> I can deploy a kfdef as a project admin or with an edit role 
> I can point kfdef to deploy manifests from any location
> I can put a cluster rolebinding with me as a cluster admin in a repo and have a kfdef point to this repo

So I can use ODH to gain cluster admin.
