### ISSUE TITLE
Data catalog is missing from 1.0.0 release CSV `alm-examples`

### ISSUE THREAD

**Issue by tumido** [opendatahub-io/opendatahub-operator#93]
**Describe the bug**
[`deploy/olm-catalog/opendatahub/1.0.0/manifests/opendatahub-operator.v1.0.0.clusterserviceversion.yaml`](https://github.com/opendatahub-io/opendatahub-operator/blob/master/deploy/olm-catalog/opendatahub/1.0.0/manifests/opendatahub-operator.v1.0.0.clusterserviceversion.yaml) is missing the newly added components:
https://github.com/opendatahub-io/odh-manifests/tree/master/thriftserver
https://github.com/opendatahub-io/odh-manifests/tree/master/hue

**To Reproduce**
1. Install odh operator
2. Click on Provided APIs
3. Click on Create KfDef
4. Click on YAML tab
5. See it doesn't list the new components
6. Compare this to Installed Operators -> ODH -> Operator Details -> Components section which maps to [this definition](https://github.com/opendatahub-io/opendatahub-operator/blob/afb6b5caf4010154ee44cbc5cbe9bc5c7e8688d0/deploy/olm-catalog/opendatahub/1.0.0/manifests/opendatahub-operator.v1.0.0.clusterserviceversion.yaml#L225-L258) that says the data catalog applications are available.

**Expected behavior**
All components should be listed

**Screenshots**
n/a

**Additional context**
n/a

**Comment by nakfour** [comment]
@tumido we will add them in the next release.
